/** LuxeFinder — 50 new SEO ideas batch (2026-08-09). Unique FR mid-tail pages. */

type PageSection = { h2: string; body: string };
type SeoPage = {
  slug: string; title: string; h1: string; description: string;
  intent: "howto" | "brand" | "model" | "buy";
  intro: string; sections: PageSection[]; brands?: string[]; related: string[];
  locale?: string;
};

export const SEO_IDEAS_50_BATCH: SeoPage[] = [
  {
    slug: "birkin-vs-kelly-taille-budget",
    title: "Birkin ou Kelly : choisir selon taille et budget",
    h1: "Birkin vs Kelly : taille, usage et budget (pas seulement le mythe)",
    description: "Comparer Birkin et Kelly selon taille, portabilité, liquidité occasion et budget réel. Guide LuxeFinder.",
    intent: "howto",
    brands: ["hermes"],
    intro: "Kelly vs Birkin revient partout — mais la vraie question est pratique : quelle taille portez-vous, quel budget, et quelle liquidité à la revente ? Voici un cadre utile avant de chercher une offre.",
    sections: [
      { h2: "Silhouette et porté", body: "Le Birkin s’ouvre largement et se porte plutôt à la main ; le Kelly se ferme plus « bijou » et se porte souvent à l’épaule/croisé selon la taille. Demandez toujours la taille exacte (25/28/30/32/35…) : le nom seul ne suffit pas." },
      { h2: "Budget : neuf inaccessible ≠ occasion simple", body: "En occasion, l’écart dépend de cuir, hardware, année et état. Une Kelly 25 pristine peut coûter plus qu’un Birkin 35 fatigué. Fixez un plafond « rendu » (article + port + éventuelle authentification)." },
      { h2: "Liquidité à la revente", body: "Les tailles « classiques » en cuirs populaires tournent plus vite. Les couleurs très niche se négocient. Documentez facture/boîte si vous les avez — ça aide, sans prouver l’authenticité seule." },
      { h2: "Checklist avant offre", body: "Photos face/profil/coins/fermoir, mesures, provenance, délai. Refusez la pression « dernière chance »." },
      { h2: "LuxeFinder", body: "Déposez une photo et votre budget pour comparer des pistes vendeurs. LuxeFinder ne vend pas et n’authentifie pas automatiquement." },
    ],
    related: ["kelly-vs-birkin","prix-birkin-occasion","prix-kelly-occasion","hermes-occasion"],
  },
  {
    slug: "neverfull-vs-onthego",
    title: "Neverfull ou OnTheGo : quel cabas LV choisir",
    h1: "Neverfull vs OnTheGo : cabas Louis Vuitton comparés",
    description: "Différences Neverfull / OnTheGo : structure, anses, usage quotidien, prix occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["louis_vuitton"],
    intro: "Deux cabas Monogram iconiques, deux attitudes : Neverfull souple et ouvert, OnTheGo plus structuré avec anses contrastées. Voici comment trancher.",
    sections: [
      { h2: "Structure et maintien", body: "Neverfull s’affaisse une fois rempli ; OnTheGo tient mieux la forme. Si vous portez un ordi, testez la rigidité sur photos de côté." },
      { h2: "Anses et confort", body: "OnTheGo mise sur de longues anses et souvent un porté épaule plus stable. Neverfull reste le réflexe « tout jeter dedans »." },
      { h2: "Prix occasion", body: "Comparez taille (PM/MM/GM vs formats OTG) + toile + état des coins. Un prix « trop beau » sur OTG neuf d’apparence mérite plus de preuves." },
      { h2: "Choisir selon usage", body: "Marché / week-end léger : Neverfull. Bureau / look plus construit : OnTheGo." },
      { h2: "LuxeFinder", body: "Photo + budget → offres vendeurs à comparer, sans achat à l’aveugle." },
    ],
    related: ["taille-neverfull-pm-mm-gm","prix-neverfull-occasion","louis-vuitton-occasion","identifier-neverfull-photo"],
  },
  {
    slug: "classic-flap-vs-boy-chanel",
    title: "Chanel Classic Flap ou Boy : comparatif",
    h1: "Classic Flap vs Boy Chanel : lequel choisir",
    description: "Classic Flap vs Boy : porté, hardware, liquidité occasion, budget. Guide LuxeFinder.",
    intent: "howto",
    brands: ["chanel"],
    intro: "Deux icônes Chanel : le Classic Flap (héritage 2.55 / Double C) et le Boy (chaîne chunky, esprit rock). Le choix dépend du style… et du marché d’occasion.",
    sections: [
      { h2: "Codes visuels", body: "Classic : matelassé diamant, chaîne gainée, fermoir CC. Boy : chainette large, fermoir rectangulaire, souvent plus « statement »." },
      { h2: "Porté quotidien", body: "Le Classic Medium reste une référence bureau/soirée. Le Boy peut paraître plus lourd selon la taille." },
      { h2: "Occasion et liquidité", body: "Classic Flap en caviar noir hardware doré reste très liquide. Boy : vérifiez taille et état de la chaîne (usure)." },
      { h2: "Budget", body: "Les hausses boutique poussent l’occasion — comparez 5 annonces équivalentes avant d’offrir." },
      { h2: "LuxeFinder", body: "Identifiez le modèle sur photo, puis comparez les offres dans votre fourchette." },
    ],
    related: ["prix-chanel-timeless-occasion","chanel-caviar-ou-agneau","chanel-occasion","augmentation-prix-chanel"],
  },
  {
    slug: "lady-dior-vs-book-tote",
    title: "Lady Dior ou Book Tote : quel Dior",
    h1: "Lady Dior vs Book Tote : élégance vs cabas",
    description: "Comparer Lady Dior et Book Tote : usage, cannage, prix occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["dior"],
    intro: "Lady Dior = icône couture à anse ; Book Tote = cabas brodé du quotidien. Deux Dior, deux vies.",
    sections: [
      { h2: "Silhouettes", body: "Lady : structure, charms D.I.O.R, cannage. Book Tote : ouvert, grand volume, motifs brodés." },
      { h2: "Usage", body: "Soirée / investissement symbolique : Lady. Ville / plage / quotidien : Book Tote." },
      { h2: "Occasion", body: "Vérifiez usure des coins Lady et état des broderies Book Tote (fils tirés)." },
      { h2: "Budget", body: "Fixez un plafond et exigez photos récentes du lot réel." },
      { h2: "LuxeFinder", body: "Photo + budget pour remonter des pistes vendeurs." },
    ],
    related: ["authentifier-sac-dior","dior","sac-de-luxe-investissement"],
  },
  {
    slug: "alma-vs-speedy",
    title: "Alma ou Speedy Louis Vuitton",
    h1: "Alma vs Speedy : deux classiques LV",
    description: "Alma BB/PM vs Speedy 25/30 : forme, fermeture, usage, occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["louis_vuitton"],
    intro: "Alma (dôme, double zip) et Speedy (duffle ouvert/zippé selon version) répondent à des gestes différents.",
    sections: [
      { h2: "Forme", body: "Alma protège mieux le contenu (zip). Speedy privilégie l’accès rapide et le volume horizontal." },
      { h2: "Tailles", body: "Alma BB vs Speedy 25 : city bag. Alma PM / Speedy 30 : quotidien." },
      { h2: "Occasion", body: "Surveillez vachetta (Alma/Speedy mono) et coins. Demandez code date / cohérence époque." },
      { h2: "Choisir", body: "Transport sécurisé (pluie, métro) : Alma. Style « grab and go » : Speedy." },
      { h2: "LuxeFinder", body: "Cadrez le modèle sur photo avant de négocier." },
    ],
    related: ["speedy-25-30-35-quelle-taille","code-date-louis-vuitton","louis-vuitton-occasion"],
  },
  {
    slug: "loulou-vs-loulou-small",
    title: "Saint Laurent Loulou : taille standard ou small",
    h1: "Loulou vs Loulou Small : quelle taille YSL",
    description: "Comparer les tailles du Saint Laurent Loulou : porté, volume, prix occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["saint_laurent"],
    intro: "Le Loulou change de look selon la taille. Small = statement ; formats plus grands = quotidien.",
    sections: [
      { h2: "Proportion", body: "Small remonte plus haut sur le buste ; medium/large descendent et portent plus." },
      { h2: "Matelassé et fermoir", body: "Vérifiez chevron, monogramme YSL, état du rabat — points d’usure classiques." },
      { h2: "Occasion", body: "Chaîne et coins : zones critiques. Comparez coloris (noir le plus liquide)." },
      { h2: "Budget", body: "Annoncez une fourchette ; refusez les catalogues génériques sans photo du lot." },
      { h2: "LuxeFinder", body: "Uploadez une photo pour confirmer le format avant de contacter un vendeur." },
    ],
    related: ["saint-laurent","trouver-vendeur-sac-luxe"],
  },
  {
    slug: "jodie-vs-andiamo",
    title: "Bottega Jodie ou Andiamo",
    h1: "Jodie vs Andiamo Bottega Veneta",
    description: "Mini Jodie intrecciato vs Andiamo : volume, style, cote occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["bottega_veneta"],
    intro: "Deux lectures Bottega : la Jodie nouée (mini/it-bag) et l’Andiamo (weekender intrecciato Blazy).",
    sections: [
      { h2: "Volume", body: "Jodie = essentiel minimal. Andiamo = journée / voyage court." },
      { h2: "Craft", body: "Intrecciato : regardez régularité du tressage et teinte du cuir sous différentes lumières." },
      { h2: "Marché", body: "Jodie a une longue piste d’occasion ; Andiamo est plus récent — rareté relative possible." },
      { h2: "Choix", body: "Soirée / micro : Jodie. Quotidien capacieux : Andiamo." },
      { h2: "LuxeFinder", body: "Photo + budget pour comparer les offres." },
    ],
    related: ["bottega-veneta","sac-de-luxe-investissement"],
  },
  {
    slug: "love-vs-juste-un-clou",
    title: "Cartier LOVE ou Juste un Clou",
    h1: "LOVE vs Juste un Clou Cartier : quel symbole",
    description: "Comparer bracelet LOVE et Juste un Clou : histoire, porté, occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["cartier"],
    intro: "Deux icônes Cipullo : le LOVE (vis, tournevis) et Juste un Clou (clou d’or). Style et message diffèrent.",
    sections: [
      { h2: "Symbolique", body: "LOVE = attachement / geste à deux. Clou = audace industrielle devenue joaillerie." },
      { h2: "Porté", body: "LOVE manchette rigide ; Clou plus « open » selon version. Essayez le confort poignet." },
      { h2: "Occasion", body: "Exigez facture, écrin, et macros des poinçons. Méfiez-vous des prix irréalistes." },
      { h2: "Variantes", body: "Or jaune / rose / blanc, diamants, mini — le prix varie fortement." },
      { h2: "LuxeFinder", body: "Une photo nette du bijou aide à cadrer le modèle avant de chercher un vendeur." },
    ],
    related: ["cartier","identifier-bijou-cartier-photo","guide-bracelets-cartier-love-clou-clash"],
  },
  {
    slug: "alhambra-vs-serpenti",
    title: "Alhambra VCA ou Serpenti Bulgari",
    h1: "Alhambra vs Serpenti : deux talismans joailliers",
    description: "Van Cleef Alhambra vs Bulgari Serpenti : codes, occasion, identification. Guide LuxeFinder.",
    intent: "howto",
    brands: ["van_cleef","bulgari"],
    intro: "Trèfle porte-bonheur (Alhambra, 1968) contre serpent métamorphose (Serpenti, 1948) : deux mythologies, deux looks.",
    sections: [
      { h2: "Codes", body: "Alhambra : motifs trèfle perlés, nacre/malachite…. Serpenti : écailles, tubogas ou Viper géométrique." },
      { h2: "Porté", body: "Alhambra souvent délicat au quotidien ; Serpenti plus sculptural." },
      { h2: "Occasion", body: "Poinçons, fermoirs, régularité des motifs. Demandez photos macro." },
      { h2: "Budget", body: "Nombre de motifs (Alhambra) et présence de diamants (Serpenti) changent tout." },
      { h2: "LuxeFinder", body: "Photo + fourchette pour explorer des offres." },
    ],
    related: ["van-cleef","alhambra-tailles-motifs","serpenti-viper-vs-tubogas"],
  },
  {
    slug: "sac-luxe-premier-achat-quelle-marque",
    title: "Premier sac de luxe : quelle marque choisir",
    h1: "Premier sac de luxe : marque, budget et usage",
    description: "Choisir sa première marque de sac luxe selon budget, usage et revente. Guide LuxeFinder.",
    intent: "howto",
    intro: "Le premier sac de luxe n’est pas un trophée Instagram : c’est un usage + un budget + une liquidité. Voici une méthode simple.",
    sections: [
      { h2: "Partir de l’usage", body: "Bureau, voyage, soirée : la marque suit le besoin, pas l’inverse." },
      { h2: "Budget réaliste", body: "Incluez occasion vs neuf. Beaucoup commencent en occasion contrôlée." },
      { h2: "Liquidité", body: "LV Neverfull/Speedy, Chanel Classic, Hermès (si budget) : plus faciles à revendre que niches extrêmes." },
      { h2: "Preuves", body: "Photos, provenance, éventuelle authentification tierce avant gros tickets." },
      { h2: "LuxeFinder", body: "Testez l’app avec une photo d’inspiration et un plafond clair." },
    ],
    related: ["premier-sac-de-luxe","sac-de-luxe-moins-1000-euros","budget-sac-luxe"],
  },
  {
    slug: "prix-alma-bb-occasion-2026",
    title: "Prix Alma BB occasion 2026",
    h1: "Prix Louis Vuitton Alma BB en occasion (repères 2026)",
    description: "Fourchettes et facteurs de prix Alma BB occasion : état, toile, hardware. Guide LuxeFinder.",
    intent: "buy",
    brands: ["louis_vuitton"],
    intro: "L’Alma BB reste très demandée. Les prix d’occasion varient surtout selon toile, état de la vachetta et complétude (bandoulière, dustbag).",
    sections: [
      { h2: "Ce qui fait monter le prix", body: "État mint, coins propres, mono classique, accessoires complets." },
      { h2: "Ce qui fait baisser", body: "Taches vachetta, coins écrasés, odeur, réparation visible." },
      { h2: "Méthode", body: "Relevez 5 annonces comparables (même toile/état) sur 2 plateformes avant d’offrir." },
      { h2: "Pièges", body: "Photos de catalogue ≠ lot réel. Exigez timestamps / détails récents." },
      { h2: "LuxeFinder", body: "Photo du modèle + budget pour comparer des vendeurs." },
    ],
    related: ["prix-neverfull-occasion","louis-vuitton-occasion","alma-vs-speedy"],
  },
  {
    slug: "prix-pochette-metis-occasion",
    title: "Prix Pochette Métis occasion",
    h1: "Prix Pochette Métis en occasion : comment lire le marché",
    description: "Repères prix Pochette Métis occasion, Empreinte vs Monogram, état. Guide LuxeFinder.",
    intent: "buy",
    brands: ["louis_vuitton"],
    intro: "Best-seller LV, la Métis se négocie fort en occasion. Empreinte, mono et éditions limitées n’ont pas la même cote.",
    sections: [
      { h2: "Variantes", body: "Monogram canvas vs Empreinte cuir : textures et usures différentes." },
      { h2: "Points d’usure", body: "Coins, bandoulière, fermoir S-lock, intérieur." },
      { h2: "Fourchettes", body: "Comparez annonces équivalentes ; ignorez les outliers sans preuves." },
      { h2: "Négociation", body: "Manques (dustbag, sangle) = levier, pas forcément red flag." },
      { h2: "LuxeFinder", body: "Cadrez le modèle sur photo puis filtrez par budget." },
    ],
    related: ["louis-vuitton-occasion","code-date-louis-vuitton","estimer-prix-sac-photo"],
  },
  {
    slug: "prix-chanel-woc-occasion",
    title: "Prix Chanel WOC occasion",
    h1: "Prix Chanel Wallet on Chain (WOC) en occasion",
    description: "Marché occasion Chanel WOC : caviar, lambskin, hardware, hausses boutique. Guide LuxeFinder.",
    intent: "buy",
    brands: ["chanel"],
    intro: "La WOC est l’entrée « iconique » Chanel pour beaucoup d’acheteurs. L’occasion suit les hausses boutique — sans être un prix unique.",
    sections: [
      { h2: "Matières", body: "Caviar vs agneau : entretien et patine différents." },
      { h2: "Hardware", body: "Doré / argenté / ruthénium : liquidité variable selon mode." },
      { h2: "État", body: "Chaîne, coins, intérieur carte : inspectez en macro." },
      { h2: "Marché", body: "Comparez 5 lots similaires avant d’enchérir mentalement." },
      { h2: "LuxeFinder", body: "Photo + budget → pistes vendeurs." },
    ],
    related: ["prix-chanel-timeless-occasion","augmentation-prix-chanel","chanel-occasion"],
  },
  {
    slug: "prix-bottega-jodie-occasion",
    title: "Prix Bottega Jodie occasion",
    h1: "Prix Bottega Veneta Jodie en occasion",
    description: "Cote occasion Mini/Small Jodie : intrecciato, couleur, état. Guide LuxeFinder.",
    intent: "buy",
    brands: ["bottega_veneta"],
    intro: "La Jodie a saturé le marché puis s’est stabilisée. Couleur et taille (mini vs small) pilotent encore le prix.",
    sections: [
      { h2: "Tailles", body: "Mini = soirée ; Small = un peu plus utilitaire." },
      { h2: "Cuir", body: "Intrecciato : rayures, détente du nœud, teinte irrégulière." },
      { h2: "Couleurs", body: "Noir / fondants liquides ; couleurs mode = plus volatiles." },
      { h2: "Preuves", body: "Photos de la base et du nœud obligatoires." },
      { h2: "LuxeFinder", body: "Identifiez le format sur photo avant de négocier." },
    ],
    related: ["jodie-vs-andiamo","bottega-veneta","cote-revente-sac-luxe-2026"],
  },
  {
    slug: "cote-revente-sac-luxe-2026",
    title: "Cote revente sacs de luxe 2026",
    h1: "Cote de revente des sacs de luxe en 2026",
    description: "Quels sacs se revendent bien en 2026, quels facteurs de cote, comment estimer. Guide LuxeFinder.",
    intent: "howto",
    intro: "La « cote » n’est pas une bourse officielle : c’est un consensus d’annonces vendues (pas seulement affichées). Voici comment la lire en 2026.",
    sections: [
      { h2: "Méthode", body: "Regardez les ventes réalisées / fourchettes serrées, pas une seule annonce rêveuse." },
      { h2: "Facteurs", body: "Marque, modèle, taille, matière, état, complétude, saisonnalité." },
      { h2: "Tendances", body: "Classiques noirs liquides ; couleurs flash plus risquées." },
      { h2: "Frais", body: "Commissions plateformes, port, éventuelle auth : nettoyez le « prix vendeur »." },
      { h2: "LuxeFinder", body: "Estimez le modèle sur photo, puis comparez des offres actuelles." },
    ],
    related: ["sac-luxe-qui-prend-de-la-valeur","sac-luxe-qui-perd-de-la-valeur","sac-de-luxe-investissement"],
  },
  {
    slug: "sac-luxe-qui-prend-de-la-valeur",
    title: "Sacs de luxe qui prennent de la valeur",
    h1: "Quels sacs de luxe prennent (parfois) de la valeur",
    description: "Icônes et conditions où un sac peut s’apprécier : rareté, hausses, état. Guide LuxeFinder.",
    intent: "howto",
    intro: "Aucun sac n’est un placement garanti. Certains modèles iconiques suivent mieux les hausses boutique — sous conditions strictes d’état et de liquidité.",
    sections: [
      { h2: "Profils souvent cités", body: "Certaines Kelly/Birkin, Classic Flap historiques, pièces limitées documentées." },
      { h2: "Conditions", body: "État exceptionnel, provenance, marché acheteur réel." },
      { h2: "Pièges", body: "Acheter « pour investir » une couleur morte = illiquidité." },
      { h2: "Horizon", body: "Pensez usage d’abord ; plus-value éventuelle ensuite." },
      { h2: "LuxeFinder", body: "Cadrez le modèle avant de payer une prime « investissement »." },
    ],
    related: ["cote-revente-sac-luxe-2026","sac-de-luxe-investissement","augmentation-prix-chanel"],
  },
  {
    slug: "sac-luxe-qui-perd-de-la-valeur",
    title: "Sacs de luxe qui perdent de la valeur",
    h1: "Pourquoi certains sacs de luxe perdent de la valeur",
    description: "Dépréciation : mode, usure, niches, frais de revente. Guide LuxeFinder.",
    intent: "howto",
    intro: "La plupart des sacs se déprécient à la sortie de boutique. Comprendre pourquoi évite les mauvaises surprises à la revente.",
    sections: [
      { h2: "Usure accélérée", body: "Cuirs sensibles, coins, vachetta tachée." },
      { h2: "Effet mode", body: "It-bags d’une saison saturent l’occasion." },
      { h2: "Frais", body: "Commissions + auth peuvent effacer une « bonne » cote." },
      { h2: "Comment limiter", body: "Classiques, entretien, preuves d’achat." },
      { h2: "LuxeFinder", body: "Comparez le prix demandé à des offres équivalentes avant d’acheter." },
    ],
    related: ["cote-revente-sac-luxe-2026","etat-sac-occasion","frais-caches-achat-sac-occasion"],
  },
  {
    slug: "frais-caches-achat-sac-occasion",
    title: "Frais cachés achat sac occasion",
    h1: "Frais cachés quand on achète un sac de luxe d’occasion",
    description: "Commissions, port, douane, authentification, réparation : le vrai coût. Guide LuxeFinder.",
    intent: "howto",
    intro: "Le prix affiché n’est presque jamais le coût final. Ajoutez ces lignes avant de « valider » mentalement une bonne affaire.",
    sections: [
      { h2: "Plateformes", body: "Buyer fees / shipping / taxes selon le site." },
      { h2: "Auth & après-vente", body: "Service d’authentification, cordonnier luxe, remplacement pièces." },
      { h2: "International", body: "Douane, TVA, courtier — surtout hors UE." },
      { h2: "Budget total", body: "Prix + 10–25 % de marge selon le canal n’est pas rare." },
      { h2: "LuxeFinder", body: "Indiquez un budget « rendu » pour filtrer des offres réalistes." },
    ],
    related: ["negociuer-prix-sac-occasion","budget-sac-luxe","acheter-sac-occasion-authenticite"],
  },
  {
    slug: "negociuer-prix-sac-occasion",
    title: "Négocier le prix d’un sac de luxe occasion",
    h1: "Négocier un sac de luxe d’occasion sans se faire avoir",
    description: "Arguments factuels pour négocier : défauts, marché, complétude. Guide LuxeFinder.",
    intent: "howto",
    intro: "Négocier n’est pas « lowballer » : c’est aligner le prix sur l’état et le marché comparable.",
    sections: [
      { h2: "Préparer", body: "5 annonces vendues/équivalentes + liste de défauts visibles." },
      { h2: "Arguments", body: "Coins, odeur, accessoires manquants, délai, mode de paiement." },
      { h2: "Ton", body: "Factuel, écrit, sans pression. Proposez un chiffre précis." },
      { h2: "Red flags", body: "Vendeur qui refuse toute discussion + urgency fake." },
      { h2: "LuxeFinder", body: "Ayez d’abord le modèle clair via photo pour négocier le bon objet." },
    ],
    related: ["frais-caches-achat-sac-occasion","comparer-offres-vendeurs","eviter-arnaques-vendeurs"],
  },
  {
    slug: "estimer-prix-sac-photo",
    title: "Estimer le prix d’un sac à partir d’une photo",
    h1: "Estimer un prix de sac de luxe à partir d’une photo",
    description: "Méthode pour estimer un prix occasion via photo : modèle, état, marché. LuxeFinder.",
    intent: "howto",
    intro: "Une photo ne donne pas un certificat de cote — mais elle permet de cadrer modèle + fourchette avant de parler argent.",
    sections: [
      { h2: "Identifier d’abord", body: "Sans modèle/taille/matière, toute estimation est du bruit." },
      { h2: "Lire l’état", body: "Coins, hardware, toile/cuir, symétrie, réparations." },
      { h2: "Benchmarks", body: "Annonces comparables récentes, même canal si possible." },
      { h2: "Fourchette", body: "Bas = défauts / liquidité faible ; haut = mint + demande." },
      { h2: "LuxeFinder", body: "Déposez la photo et un budget : l’app aide à trouver des offres autour de cette réalité." },
    ],
    related: ["identifier-modele-sac","cote-revente-sac-luxe-2026","comparer-offres-vendeurs"],
  },
  {
    slug: "identifier-birkin-photo",
    title: "Identifier un Birkin sur photo",
    h1: "Identifier un Hermès Birkin à partir d’une photo",
    description: "Signaux visuels Birkin : silhouette, clous, cadenas, cuir. Guide photo LuxeFinder.",
    intent: "howto",
    brands: ["hermes"],
    intro: "Sur photo, un Birkin se reconnaît à la silhouette, aux clous de pied, au rabat et au cadenas — mais la taille et le cuir se confirment en détails.",
    sections: [
      { h2: "Angles utiles", body: "Face ouverte, profil, base avec clous, plaque/cadenas, coutures." },
      { h2: "Taille", body: "Demandez mesures ou objet de référence ; 25≠30≠35." },
      { h2: "Cuir", body: "Togo, Clemence, Epsom, Swift… texture différente en macro." },
      { h2: "Pièges", body: "Sacs « style Birkin » sans codes Hermès. Refusez les zooms flous." },
      { h2: "LuxeFinder", body: "Uploadez la photo pour cadrer le modèle avant de chercher un vendeur." },
    ],
    related: ["prix-birkin-occasion","reconnaitre-vrai-hermes","hermes-occasion"],
  },
  {
    slug: "identifier-classic-flap-photo",
    title: "Identifier un Classic Flap sur photo",
    h1: "Identifier un Chanel Classic Flap sur photo",
    description: "Repères photo Classic Flap : matelassé, CC, chaîne, caviar/agneau. Guide LuxeFinder.",
    intent: "howto",
    brands: ["chanel"],
    intro: "Le Classic Flap est très copié. Une bonne photo isole matelassé, proportion, fermoir et chaîne gainée.",
    sections: [
      { h2: "Checklist visuelle", body: "Losanges réguliers, CC, chaîne, numéro/autocollant si visible, intérieur." },
      { h2: "Caviar vs agneau", body: "Grain vs douceur : change l’usure attendue." },
      { h2: "Taille", body: "Mini / small / medium… le porté change tout." },
      { h2: "Preuves vendeur", body: "Macros hardware + série + profil." },
      { h2: "LuxeFinder", body: "Photo nette → description de modèle pour comparer des offres." },
    ],
    related: ["reconnaitre-vrai-chanel-caviar","prix-chanel-timeless-occasion","numero-serie-chanel"],
  },
  {
    slug: "reconnaitre-vrai-hermes",
    title: "Reconnaître un vrai Hermès",
    h1: "Reconnaître un vrai sac Hermès : points de contrôle",
    description: "Coutures, tampon, hardware, proportions : indices d’authenticité Hermès. Guide LuxeFinder.",
    intent: "howto",
    brands: ["hermes"],
    intro: "Aucun tutorial web ne remplace un expert — mais une checklist photo évite les arnaques grossières avant de payer.",
    sections: [
      { h2: "Coutures et symétrie", body: "Point sellier, régularité, alignement des panneaux." },
      { h2: "Tampons et marquages", body: "Lisibilité, placement, cohérence avec l’époque." },
      { h2: "Hardware", body: "Gravures, couleur du métal, jeu du cadenas." },
      { h2: "Process", body: "En cas de doute : authentification professionnelle avant virement." },
      { h2: "LuxeFinder", body: "Cadrez d’abord le modèle sur photo ; l’auth reste une étape séparée." },
    ],
    related: ["faire-authentifier-un-sac","identifier-birkin-photo","hermes-occasion"],
  },
  {
    slug: "reconnaitre-vrai-chanel-caviar",
    title: "Reconnaître un vrai Chanel caviar",
    h1: "Chanel caviar authentique : ce que la photo doit montrer",
    description: "Grain caviar, coutures, série, chaîne : contrôles photo Chanel. Guide LuxeFinder.",
    intent: "howto",
    brands: ["chanel"],
    intro: "Le caviar Chanel a un grain caractéristique. Sur faux, le relief, la peinture des losanges ou le hardware trahissent souvent.",
    sections: [
      { h2: "Grain et peinture", body: "Relief régulier, pas de « plastique » brillant irrégulier." },
      { h2: "Série et stickers", body: "Cohérence typographique ; ce n’est pas une preuve unique." },
      { h2: "Chaîne", body: "Poids, gainage cuir, soudure." },
      { h2: "Croiser les indices", body: "Un seul détail OK ne suffit pas." },
      { h2: "LuxeFinder", body: "Utilisez une photo nette pour identifier le modèle, puis faites auth si le ticket est élevé." },
    ],
    related: ["chanel-caviar-ou-agneau","numero-serie-chanel","identifier-classic-flap-photo"],
  },
  {
    slug: "date-code-chanel-guide",
    title: "Date code / série Chanel : guide",
    h1: "Série et date code Chanel : lire les marquages",
    description: "Comprendre les numéros de série Chanel, autocollants, limites pour l’auth. Guide LuxeFinder.",
    intent: "howto",
    brands: ["chanel"],
    intro: "Les marquages Chanel aident à dater une pièce — ils ne « prouvent » pas seuls l’authenticité. Voici comment les lire sans surinterpréter.",
    sections: [
      { h2: "Où regarder", body: "Autocollant intérieur, hologramme selon époque, photos macro." },
      { h2: "Évolution", body: "Formats changent selon les années ; incohérence époque/style = alerte." },
      { h2: "Limites", body: "Les faux reproduisent les séries. Croisez coutures/hardware." },
      { h2: "Demande vendeur", body: "Photo du sticker + emplacement dans le sac." },
      { h2: "LuxeFinder", body: "Identifiez le modèle ; traitez la série comme un indice parmi d’autres." },
    ],
    related: ["numero-serie-chanel","reconnaitre-vrai-chanel-caviar","faire-authentifier-un-sac"],
  },
  {
    slug: "hallmark-cartier-lire",
    title: "Lire un poinçon Cartier",
    h1: "Poinçons et hallmarks Cartier : les lire sur photo",
    description: "Poinçons or, gravures Cartier, références : guide photo acheteur. LuxeFinder.",
    intent: "howto",
    brands: ["cartier"],
    intro: "Sur LOVE, Clou ou Clash, les gravures intérieures et poinçons sont des indices — pas une authentification magique.",
    sections: [
      { h2: "Quoi photographier", body: "Intérieur du bracelet/bague, poinçon, référence, largeur." },
      { h2: "Or et titres", body: "Poinçons de titre selon pays ; cohérence avec le métal annoncé." },
      { h2: "Gravure Cartier", body: "Typographie et profondeur : comparez à des références connues." },
      { h2: "Pièges", body: "Gravures trop superficielles, prix absurdes, vendeur sans facture." },
      { h2: "LuxeFinder", body: "Une macro du bijou aide à nommer la collection avant de chercher une offre." },
    ],
    related: ["cartier","love-vs-juste-un-clou","identifier-bijou-cartier-photo"],
  },
  {
    slug: "numero-serie-bottega-veneta",
    title: "Numéro / marquages Bottega Veneta",
    h1: "Marquages Bottega Veneta : ce qu’on peut vérifier sur photo",
    description: "Étiquettes, tampon, intrecciato : contrôles photo Bottega. Guide LuxeFinder.",
    intent: "howto",
    brands: ["bottega_veneta"],
    intro: "Bottega mise sur le craft intrecciato plus que sur un « date code » grand public. Voici les angles utiles.",
    sections: [
      { h2: "Intrecciato", body: "Régularité, tension, teinte." },
      { h2: "Étiquettes / tampon", body: "Lisibilité, couture, placement." },
      { h2: "Hardware", body: "Nœuds, zips, gravures selon modèle (Jodie, Andiamo…)." },
      { h2: "Preuves", body: "Photos base + intérieur + profil." },
      { h2: "LuxeFinder", body: "Identifiez d’abord Jodie vs Andiamo vs autre sur photo." },
    ],
    related: ["jodie-vs-andiamo","bottega-veneta","faire-authentifier-un-sac"],
  },
  {
    slug: "faux-vs-vrai-checklist-photo",
    title: "Checklist photo vrai vs faux sac luxe",
    h1: "Checklist photo : indices vrai vs faux (sac de luxe)",
    description: "Grille photo anti-arnaque : angles, macros, cohérence. Guide LuxeFinder.",
    intent: "howto",
    intro: "Avant de parler prix, exigez une grille photo minimale. Beaucoup d’arnaques meurent là.",
    sections: [
      { h2: "Angles obligatoires", body: "Face, dos, profil, base, intérieur, hardware, défauts." },
      { h2: "Macros", body: "Coutures, logo, numéro, zip." },
      { h2: "Cohérence", body: "Usure intérieure = usure extérieure ?" },
      { h2: "Process", body: "Paiement protégé / auth escrow sur gros tickets." },
      { h2: "LuxeFinder", body: "Partez d’une photo claire pour nommer le modèle, puis appliquez la checklist au lot vendeur." },
    ],
    related: ["photos-vendeur-quelles-demander","eviter-arnaques-vendeurs","signaux-arnaque-leboncoin-sac-luxe"],
  },
  {
    slug: "signaux-arnaque-leboncoin-sac-luxe",
    title: "Arnaques Leboncoin sacs de luxe",
    h1: "Leboncoin & sacs de luxe : signaux d’arnaque",
    description: "Red flags annonces Leboncoin luxe : prix, photos, livraison, paiement. Guide LuxeFinder.",
    intent: "howto",
    intro: "Leboncoin peut être utile — et piégé. Voici les signaux qui doivent freiner immédiatement.",
    sections: [
      { h2: "Prix trop beaux", body: "Classic Flap mint à prix « soldes » sans story = danger." },
      { h2: "Photos", body: "Stock Google, flou, refus de live photo." },
      { h2: "Paiement", body: "Hors plateforme, liens suspects, urgence." },
      { h2: "Remise", body: "Lieu public / auth avant solde sur montants élevés." },
      { h2: "LuxeFinder", body: "Vérifiez d’abord que le modèle de l’annonce correspond vraiment à la photo." },
    ],
    related: ["eviter-arnaques-vendeurs","faux-vs-vrai-checklist-photo","sac-luxe-occasion-france"],
  },
  {
    slug: "photos-vendeur-quelles-demander",
    title: "Quelles photos demander à un vendeur de sac",
    h1: "Quelles photos exiger avant d’acheter un sac de luxe",
    description: "Liste de photos vendeur : angles, macros, preuves. Guide LuxeFinder.",
    intent: "howto",
    intro: "Une annonce avec 3 photos Instagram ne suffit pas. Copiez-collez cette liste au vendeur.",
    sections: [
      { h2: "Liste courte", body: "Face, profil, ouverts, coins, anses, intérieur, hardware, numéro." },
      { h2: "Liste plus", body: "Balance, lumière du jour, vidéo 10s, accessoire (dustbag)." },
      { h2: "Timestamps", body: "Demandez une photo avec un papier daté si doute." },
      { h2: "Refus", body: "Si le vendeur refuse tout détail : passez." },
      { h2: "LuxeFinder", body: "Vous pouvez aussi partir de votre propre photo d’inspiration pour cibler le bon modèle." },
    ],
    related: ["faux-vs-vrai-checklist-photo","comparer-offres-vendeurs","acheter-sac-occasion-authenticite"],
  },
  {
    slug: "identifier-bijou-cartier-photo",
    title: "Identifier un bijou Cartier sur photo",
    h1: "Identifier LOVE, Clou, Clash… sur une photo",
    description: "Reconnaître les collections Cartier sur photo produit. Guide LuxeFinder.",
    intent: "howto",
    brands: ["cartier"],
    intro: "Vis, clou, picots Clash : les silhouettes Cartier sont très lisibles — encore faut-il la bonne macro.",
    sections: [
      { h2: "LOVE", body: "Têtes de vis sur bande plate." },
      { h2: "Juste un Clou", body: "Tête + pointe de clou." },
      { h2: "Clash", body: "Studs / pyramides." },
      { h2: "Preuves", body: "Poinçon, écrin, facture." },
      { h2: "LuxeFinder", body: "Déposez la photo pour cadrer la collection avant de chercher un vendeur." },
    ],
    related: ["love-vs-juste-un-clou","hallmark-cartier-lire","guide-bracelets-cartier-love-clou-clash"],
  },
  {
    slug: "guide-bracelets-cartier-love-clou-clash",
    title: "Guide bracelets Cartier LOVE Clou Clash",
    h1: "Bracelets Cartier : LOVE, Juste un Clou, Clash",
    description: "Panorama des bracelets Cartier iconiques : histoire courte, porté, occasion. LuxeFinder.",
    intent: "howto",
    brands: ["cartier"],
    intro: "Trois piliers contemporains : LOVE (1969), Juste un Clou (1971/relance), Clash (2019). Voici le mode d’emploi acheteur.",
    sections: [
      { h2: "Chronologie", body: "Cipullo → relances → Clash comme pilier moderne." },
      { h2: "Choisir", body: "Discret vs statement vs architectural." },
      { h2: "Occasion", body: "Or rose très demandé ; diamants = ticket plus élevé." },
      { h2: "Vérifs", body: "Macros + poinçons + cohérence du prix." },
      { h2: "LuxeFinder", body: "Photo du poignet / du bijou pour nommer la ligne." },
    ],
    related: ["cartier","love-vs-juste-un-clou","identifier-bijou-cartier-photo"],
  },
  {
    slug: "alhambra-tailles-motifs",
    title: "Alhambra : tailles et nombre de motifs",
    h1: "Van Cleef Alhambra : motifs, tailles et portés",
    description: "Bracelet 5 motifs, colliers, Vintage vs Sweet Alhambra. Guide LuxeFinder.",
    intent: "howto",
    brands: ["van_cleef"],
    intro: "Le nombre de motifs et la taille (Vintage, Sweet, Magic…) changent prix et look. Clarifiez avant d’acheter.",
    sections: [
      { h2: "Bracelet 5 motifs", body: "Classique quotidien nacre / malachite." },
      { h2: "Colliers", body: "Nombre de motifs et longueur pilotent le prix." },
      { h2: "Matériaux", body: "Nacre, cornaline, onyx, diamants…" },
      { h2: "Occasion", body: "Fermoir, usure des bords perlés, authenticité poinçons." },
      { h2: "LuxeFinder", body: "Photo nette des motifs pour confirmer la ligne." },
    ],
    related: ["alhambra-vs-serpenti","van-cleef"],
  },
  {
    slug: "serpenti-viper-vs-tubogas",
    title: "Serpenti Viper ou Tubogas",
    h1: "Bulgari Serpenti : Viper vs Tubogas",
    description: "Différences Serpenti Viper et Tubogas : style, flexibilité, occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["bulgari"],
    intro: "Tubogas = spirale flexible historique ; Viper = lecture géométrique contemporaine. Deux Serpenti, deux silhouettes.",
    sections: [
      { h2: "Tubogas", body: "Anneaux continus, héritage montre-bracelet." },
      { h2: "Viper", body: "Écailles trapézoïdales, souvent tête/queue diamants." },
      { h2: "Porté", body: "Flexibilité et volume différents au poignet." },
      { h2: "Occasion", body: "Or rose pavé = ticket ; exigez macros." },
      { h2: "LuxeFinder", body: "Photo pour distinguer la ligne avant la chasse aux offres." },
    ],
    related: ["alhambra-vs-serpenti"],
  },
  {
    slug: "lunettes-cartier-panthere-guide",
    title: "Guide lunettes Cartier Panthère",
    h1: "Lunettes Cartier Panthère : repères acheteur",
    description: "Panthère de Cartier eyewear : motifs, formes, occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["cartier"],
    intro: "Têtes de panthère aux charnières, cat-eye, aviator ou rimless : la ligne Panthère est un marqueur fort.",
    sections: [
      { h2: "Signature", body: "Panthère 3D, signature sur verre, finitions or." },
      { h2: "Formes", body: "Cat-eye, pilot, rimless rectangulaire." },
      { h2: "Occasion", body: "État des embouts, rayures verres, authenticité gravures." },
      { h2: "Budget", body: "Comparez métal vs acétate." },
      { h2: "LuxeFinder", body: "Photo face + branche pour identifier le modèle." },
    ],
    related: ["cartier","acheter-lunettes-luxe-occasion"],
  },
  {
    slug: "acheter-lunettes-luxe-occasion",
    title: "Acheter des lunettes de luxe d’occasion",
    h1: "Lunettes de luxe d’occasion : checklist",
    description: "Acheter Chanel, Dior, Cartier, YSL en occasion : états, preuves, arnaques. Guide LuxeFinder.",
    intent: "buy",
    intro: "Les solaires luxe circulent beaucoup en occasion — avec un taux d’usure et de copies non négligeable. Voici la checklist.",
    sections: [
      { h2: "État optique", body: "Rayures, décollement verres, branches tordues." },
      { h2: "Preuves", body: "Étui, cloth, facture, gravures intérieures." },
      { h2: "Essayage", body: "Si possible ; sinon mesures pont/largeur." },
      { h2: "Prix", body: "Trop beau sur Panthère mint = frein." },
      { h2: "LuxeFinder", body: "Identifiez le modèle sur photo avant de payer." },
    ],
    related: ["lunettes-cartier-panthere-guide","reconnaitre-vraies-lunettes-dior"],
  },
  {
    slug: "reconnaitre-vraies-lunettes-dior",
    title: "Reconnaître de vraies lunettes Dior",
    h1: "Lunettes Dior authentiques : indices photo",
    description: "CD, Cannage, gravures : repères pour solaires Dior. Guide LuxeFinder.",
    intent: "howto",
    brands: ["dior"],
    intro: "Logo CD, Cannage sur branches, gravures intérieures : autant d’indices à croiser, jamais un seul.",
    sections: [
      { h2: "Branding", body: "CD charnière, wordmark Dior, Cannage." },
      { h2: "Finition", body: "Alignement, qualité acétate/métal." },
      { h2: "Packaging", body: "Utile mais falsifiable." },
      { h2: "Process", body: "Gros ticket → opticien / auth." },
      { h2: "LuxeFinder", body: "Photo claire pour nommer Thèse, Club, 30Montaigne…" },
    ],
    related: ["acheter-lunettes-luxe-occasion","dior"],
  },
  {
    slug: "prada-symbole-vs-prada-classique",
    title: "Prada Symbole vs montures classiques",
    h1: "Prada Symbole ou Prada classique : quelle monture",
    description: "Ligne Symbole vs silhouettes Prada plus discrètes : style et occasion. Guide LuxeFinder.",
    intent: "howto",
    brands: ["prada"],
    intro: "Symbole pousse le logo et les formes géométriques ; d’autres montures Prada restent plus minimalistes. Tranchez selon le look.",
    sections: [
      { h2: "Symbole", body: "Rectangle bold, branding Milano visible." },
      { h2: "Classique", body: "Lignes plus sobres, logo discret." },
      { h2: "Occasion", body: "Vérifiez branches et gravures." },
      { h2: "Usage", body: "Statement street vs quotidien discret." },
      { h2: "LuxeFinder", body: "Photo de profil pour lire le logo branche." },
    ],
    related: ["acheter-lunettes-luxe-occasion"],
  },
  {
    slug: "sac-luxe-occasion-paris",
    title: "Sac de luxe occasion à Paris",
    h1: "Acheter un sac de luxe d’occasion à Paris",
    description: "Paris occasion luxe : quartiers, réflexes, auth, budget. Guide LuxeFinder.",
    intent: "buy",
    intro: "Paris concentre boutiques dépôt-vente, rendez-vous particuliers et arnaques. Voici un cadre local.",
    sections: [
      { h2: "Canaux", body: "Dépôt-vente, plateformes, rendez-vous sécurisés." },
      { h2: "Quartiers", body: "Densité d’offres ≠ qualité : vérifiez toujours la pièce." },
      { h2: "Auth", body: "Prévoyez un créneau expert si ticket élevé." },
      { h2: "Budget", body: "Ajoutez transport / auth au plafond." },
      { h2: "LuxeFinder", body: "Préparez le modèle sur photo avant de sillonner Paris." },
    ],
    related: ["sac-luxe-occasion-france","meilleures-boutiques-occasion-luxe-france","ou-acheter-sac-luxe-occasion-lyon"],
  },
  {
    slug: "ou-acheter-sac-luxe-occasion-lyon",
    title: "Sac de luxe occasion à Lyon",
    h1: "Où acheter un sac de luxe d’occasion à Lyon",
    description: "Pistes occasion luxe à Lyon : réflexes acheteur, preuves, budget. Guide LuxeFinder.",
    intent: "buy",
    intro: "Moins dense que Paris, Lyon a tout de même dépôt-vente et particuliers. La méthode reste photo + preuves + budget.",
    sections: [
      { h2: "Canaux locaux", body: "Dépôt-vente, annonces, plateformes nationales avec retrait." },
      { h2: "Contrôles", body: "Même checklist photo qu’ailleurs." },
      { h2: "Remise", body: "Lieu public, lumière du jour." },
      { h2: "Auth", body: "Envisagez envoi expert si doute." },
      { h2: "LuxeFinder", body: "Cadrez le modèle avant de déplacer." },
    ],
    related: ["sac-luxe-occasion-paris","sac-luxe-occasion-france"],
  },
  {
    slug: "meilleures-boutiques-occasion-luxe-france",
    title: "Boutiques occasion luxe en France",
    h1: "Boutiques et circuits d’occasion luxe en France",
    description: "Comment choisir un circuit occasion (dépôt-vente, plateforme, pro) en France. Guide LuxeFinder.",
    intent: "howto",
    intro: "Il n’existe pas de classement unique « meilleur » : il existe des circuits adaptés à votre ticket et votre tolérance au risque.",
    sections: [
      { h2: "Dépôt-vente", body: "Voir la pièce, parfois garanties locales." },
      { h2: "Plateformes", body: "Large choix, frais, auth variable." },
      { h2: "Pro / expert", body: "Plus cher, plus de process." },
      { h2: "Critères", body: "Politique retour, auth, transparence défauts." },
      { h2: "LuxeFinder", body: "Identifiez le modèle, puis choisissez le circuit." },
    ],
    related: ["meilleurs-sites-sac-luxe-occasion","sac-luxe-occasion-france","vestiaire-collective-fiable"],
  },
  {
    slug: "sac-luxe-occasion-belgique",
    title: "Sac de luxe occasion en Belgique",
    h1: "Acheter un sac de luxe d’occasion en Belgique",
    description: "Occasion luxe Belgique : canaux, livraison UE, contrôles. Guide LuxeFinder.",
    intent: "buy",
    intro: "Depuis la Belgique, le marché UE facilite beaucoup d’achats — les arnaques, elles, ne connaissent pas les frontières.",
    sections: [
      { h2: "Canaux", body: "Locaux + plateformes EU." },
      { h2: "Livraison", body: "Restez attentif aux frais et assurances." },
      { h2: "Contrôles", body: "Checklist photo + auth si besoin." },
      { h2: "Paiement", body: "Traces écrites, protection acheteur." },
      { h2: "LuxeFinder", body: "Photo + budget en EUR." },
    ],
    related: ["sac-luxe-occasion-suisse","importer-sac-luxe-ue-regles"],
  },
  {
    slug: "sac-luxe-occasion-suisse",
    title: "Sac de luxe occasion en Suisse",
    h1: "Sac de luxe d’occasion en Suisse : points d’attention",
    description: "Occasion luxe Suisse : prix, douane vers UE, preuves. Guide LuxeFinder.",
    intent: "buy",
    intro: "La Suisse attire pour l’offre — mais franchir la frontière vers l’UE implique règles et coûts potentiels.",
    sections: [
      { h2: "Prix affichés", body: "Comparez en devise et frais totaux." },
      { h2: "Douane / TVA", body: "Anticipez si import UE." },
      { h2: "Preuves", body: "Facture, auth, état." },
      { h2: "Remise locale", body: "Toujours inspecter en main propre si possible." },
      { h2: "LuxeFinder", body: "Cadrez le modèle avant de voyager pour un essai." },
    ],
    related: ["sac-luxe-occasion-belgique","importer-sac-luxe-ue-regles","frais-caches-achat-sac-occasion"],
  },
  {
    slug: "tva-marge-occasion-luxe-france",
    title: "TVA sur marge occasion luxe France",
    h1: "TVA sur marge et occasion luxe en France : bases acheteur",
    description: "Comprendre la TVA sur marge côté acheteur occasion (informational). Guide LuxeFinder.",
    intent: "howto",
    intro: "En occasion professionnelle, la TVA sur marge peut s’appliquer. Ce n’est pas un conseil fiscal — juste des bases pour lire une facture.",
    sections: [
      { h2: "Pourquoi ça existe", body: "Régime adapté aux biens d’occasion sous conditions." },
      { h2: "Ce que voit l’acheteur", body: "Prix TTC souvent ; demandez une facture claire." },
      { h2: "Particulier vs pro", body: "Les règles et documents diffèrent." },
      { h2: "Action", body: "En cas de doute, expert-comptable / fiscaliste." },
      { h2: "LuxeFinder", body: "Concentrez-vous d’abord sur le bon modèle et un budget net." },
    ],
    related: ["frais-caches-achat-sac-occasion","sac-luxe-occasion-france"],
  },
  {
    slug: "importer-sac-luxe-ue-regles",
    title: "Importer un sac de luxe dans l’UE",
    h1: "Importer un sac de luxe dans l’UE : règles de base",
    description: "Douane, TVA, seuils : bases pour un achat luxe hors/dans UE. Guide informatif LuxeFinder.",
    intent: "howto",
    intro: "Acheter hors UE peut sembler moins cher — jusqu’aux frais de dédouanement. Cadrez avant de cliquer.",
    sections: [
      { h2: "Dans l’UE", body: "Circulation plus simple, mais vendeur et TVA selon cas." },
      { h2: "Hors UE", body: "Droits / TVA / frais de dossier possibles." },
      { h2: "Déclaration", body: "Valeur réelle, facture, tracking." },
      { h2: "Risques", body: "Saisie si non-conformité / contrefaçon suspectée." },
      { h2: "LuxeFinder", body: "Outil pour trouver des offres ; le respect douanier reste votre responsabilité." },
    ],
    related: ["frais-caches-achat-sac-occasion","acheter-sac-luxe-japon"],
  },
  {
    slug: "glossaire-codes-materiaux-luxe",
    title: "Glossaire matériaux sacs de luxe",
    h1: "Glossaire : caviar, Togo, intrecciato, vachetta…",
    description: "Lexique matériaux et codes sacs luxe pour mieux lire une annonce. Guide LuxeFinder.",
    intent: "howto",
    intro: "Mal nommer un cuir fait dériver le prix. Ce glossaire court aide à décoder les annonces.",
    sections: [
      { h2: "Cuirs Hermès (aperçu)", body: "Togo, Clemence, Epsom, Swift : grains et tenue." },
      { h2: "Chanel", body: "Caviar vs agneau." },
      { h2: "LV", body: "Vachetta, mono, Damier." },
      { h2: "Bottega", body: "Intrecciato." },
      { h2: "LuxeFinder", body: "Une photo aide quand le vocabulaire vendeur est flou." },
    ],
    related: ["chanel-caviar-ou-agneau","cuir-vachetta-louis-vuitton","glossaire-luxe-acheteur"],
  },
  {
    slug: "augmentations-prix-marques-luxe-2024-2026",
    title: "Hausses prix luxe 2024–2026",
    h1: "Augmentations des prix du luxe 2024–2026 : effet occasion",
    description: "Comment les hausses boutique 2024–2026 tirent (ou non) l’occasion. Guide LuxeFinder.",
    intent: "buy",
    intro: "Chanel, Hermès, LV… les hausses boutique déplacent une partie de la demande vers l’occasion. Ce n’est pas mécanique : l’état et la liquidité restent rois.",
    sections: [
      { h2: "Mécanisme", body: "Neuf plus cher → occasion plus attractive, parfois plus tendue." },
      { h2: "Pas automatique", body: "Modèles peu demandés restent soft." },
      { h2: "Stratégie acheteur", body: "Suivre 2–3 modèles max, comparer sur 30 jours." },
      { h2: "Timing", body: "Éviter l’urgence post-annonce de hausse." },
      { h2: "LuxeFinder", body: "Photo + budget pour rester ancré dans le marché réel." },
    ],
    related: ["augmentation-prix-chanel","cote-revente-sac-luxe-2026","prix-chanel-timeless-occasion"],
  },
  {
    slug: "meilleur-sac-luxe-selon-usage",
    title: "Meilleur sac de luxe selon usage",
    h1: "Quel sac de luxe selon l’usage (ville, voyage, soirée)",
    description: "Choisir un sac luxe par usage : quotidien, voyage, soirée, budget. Guide LuxeFinder.",
    intent: "howto",
    intro: "Le « meilleur » sac n’existe pas : le meilleur pour votre semaine, oui.",
    sections: [
      { h2: "Ville / bureau", body: "Structuré, accessible (Métis, Classic, Loulou…)." },
      { h2: "Voyage", body: "Cabas capacieux (Neverfull, Keepall, Andiamo…)." },
      { h2: "Soirée", body: "Petit format (WOC, mini flap, Jodie mini…)." },
      { h2: "Budget", body: "Occasion contrôlée pour démarrer." },
      { h2: "LuxeFinder", body: "Partir d’une photo d’inspiration + usage déclaré mentalement." },
    ],
    related: ["premier-sac-de-luxe","tailles-sacs-luxe","sac-luxe-premier-achat-quelle-marque"],
  },
  {
    slug: "chanel-classic-flap-2020-vs-2024",
    title: "Classic Flap 2020 vs 2024",
    h1: "Chanel Classic Flap : 2020 vs 2024 (prix et détails)",
    description: "Ce qui change entre une Classic Flap ~2020 et ~2024 : prix boutique, occasion, contrôles. Guide LuxeFinder.",
    intent: "howto",
    brands: ["chanel"],
    intro: "Entre deux millésimes, le design reste familier — le ticket boutique et parfois les détails évoluent. L’occasion doit se lire à l’aune de l’époque.",
    sections: [
      { h2: "Prix boutique", body: "Les hausses successives écartent neuf et occasion récente." },
      { h2: "Détails à comparer", body: "Hardware, série, état réel > année marketing." },
      { h2: "Occasion", body: "Une 2020 impeccable peut valoir mieux qu’une 2024 abîmée." },
      { h2: "Auth", body: "Cohérence époque / marquages." },
      { h2: "LuxeFinder", body: "Identifiez taille/matière sur photo avant de parler année." },
    ],
    related: ["augmentation-prix-chanel","prix-chanel-timeless-occasion","date-code-chanel-guide"],
  },
  {
    slug: "faq-marques-luxe-achat-occasion",
    title: "FAQ achat occasion marques de luxe",
    h1: "FAQ : acheter des marques de luxe en occasion",
    description: "Réponses courtes aux questions fréquentes sur l’occasion LV, Chanel, Hermès, Dior… LuxeFinder.",
    intent: "howto",
    intro: "Les mêmes questions reviennent : auth, prix, photos, plateformes. Voici une FAQ actionnable.",
    sections: [
      { h2: "Faut-il toujours authentifier ?", body: "Sur ticket élevé : oui. Sur petit ticket : au minimum checklist photo stricte." },
      { h2: "Neuf vs occasion", body: "Occasion = état + liquidité ; neuf = marge boutique." },
      { h2: "Quelles marques pour débuter ?", body: "Classiques liquides (voir guides premier sac)." },
      { h2: "Paiement", body: "Protection acheteur quand possible." },
      { h2: "LuxeFinder", body: "Photo + budget pour démarrer une recherche cadrée." },
    ],
    related: ["acheter-sac-occasion-authenticite","eviter-arnaques-vendeurs","meilleurs-sites-sac-luxe-occasion"],
  },
];

export function pagesIdeas50(): SeoPage[] {
  return SEO_IDEAS_50_BATCH;
}
