/** Vague 1 — auth / ID photo / vrai-ou-faux (légal). Pas de SEO transactionnel contrefaçon. */

import type { SeoPage } from "./seo-pages";

export const SEO_AUTH_ID_BATCH: SeoPage[] = [
  {
    slug: "reconnaitre-faux-neverfull",
    title: "Comment reconnaître un faux Neverfull Louis Vuitton (guide 2026)",
    h1: "Comment reconnaître un faux Neverfull",
    description: "Signes d’un faux Neverfull Louis Vuitton : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "Les contrefaçons de Neverfull (Louis Vuitton) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Louis Vuitton. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Neverfull se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Neverfull", body: "Pour un Neverfull Louis Vuitton : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Louis Vuitton. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-neverfull-photo","vrai-ou-faux-neverfull","identifier-modele-sac"],
  },

  {
    slug: "vrai-ou-faux-neverfull",
    title: "Neverfull Louis Vuitton : vrai ou faux ? Checklist",
    h1: "Neverfull : vrai ou faux ?",
    description: "Checklist vrai/faux Neverfull Louis Vuitton pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "« Neverfull vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Neverfull), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Louis Vuitton. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-neverfull","identifier-neverfull-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-speedy",
    title: "Comment reconnaître un faux Speedy Louis Vuitton (guide 2026)",
    h1: "Comment reconnaître un faux Speedy",
    description: "Signes d’un faux Speedy Louis Vuitton : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "Les contrefaçons de Speedy (Louis Vuitton) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Louis Vuitton. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Speedy se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Speedy", body: "Pour un Speedy Louis Vuitton : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Louis Vuitton. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-speedy-photo","vrai-ou-faux-speedy","identifier-modele-sac"],
  },
  {
    slug: "identifier-speedy-photo",
    title: "Identifier un Speedy Louis Vuitton sur photo",
    h1: "Identifier un Speedy à partir d’une photo",
    description: "Quel modèle est ce Speedy Louis Vuitton ? Angles utiles, détails à viser, puis analyse photo LuxeFinder.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "Mal nommer un Speedy fausse toute recherche d’occasion. Voici comment préparer une photo exploitable, puis laisser LuxeFinder proposer une identification.",
    sections: [
      { h2: "Angles qui comptent", body: "Face, profil, ouvert (intérieur), hardware, et une vue nette de la matière. Lumière naturelle, sans filtre agressif." },
      { h2: "Signaux Speedy", body: "Silhouette, anses, fermoir, proportions, toile ou cuir typiques du Speedy. Notez la taille approximative (ex. cm de base) si vous la connaissez." },
      { h2: "Passer dans LuxeFinder", body: "Uploadez la photo : l’app propose un cadrage modèle pour comparer des offres d’occasion / vendeurs — pas des catalogues de répliques." },
      { h2: "Ensuite", body: "Une fois le modèle nommé, croisez avec un guide « vrai ou faux » et exigez des photos récentes au vendeur." },
    ],
    related: ["reconnaitre-faux-speedy","vrai-ou-faux-speedy","identifier-modele-sac"],
  },
  {
    slug: "vrai-ou-faux-speedy",
    title: "Speedy Louis Vuitton : vrai ou faux ? Checklist",
    h1: "Speedy : vrai ou faux ?",
    description: "Checklist vrai/faux Speedy Louis Vuitton pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "« Speedy vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Speedy), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Louis Vuitton. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-speedy","identifier-speedy-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-keepall",
    title: "Comment reconnaître un faux Keepall Louis Vuitton (guide 2026)",
    h1: "Comment reconnaître un faux Keepall",
    description: "Signes d’un faux Keepall Louis Vuitton : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "Les contrefaçons de Keepall (Louis Vuitton) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Louis Vuitton. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Keepall se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Keepall", body: "Pour un Keepall Louis Vuitton : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Louis Vuitton. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-keepall-photo","vrai-ou-faux-keepall","identifier-modele-sac"],
  },
  {
    slug: "identifier-keepall-photo",
    title: "Identifier un Keepall Louis Vuitton sur photo",
    h1: "Identifier un Keepall à partir d’une photo",
    description: "Quel modèle est ce Keepall Louis Vuitton ? Angles utiles, détails à viser, puis analyse photo LuxeFinder.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "Mal nommer un Keepall fausse toute recherche d’occasion. Voici comment préparer une photo exploitable, puis laisser LuxeFinder proposer une identification.",
    sections: [
      { h2: "Angles qui comptent", body: "Face, profil, ouvert (intérieur), hardware, et une vue nette de la matière. Lumière naturelle, sans filtre agressif." },
      { h2: "Signaux Keepall", body: "Silhouette, anses, fermoir, proportions, toile ou cuir typiques du Keepall. Notez la taille approximative (ex. cm de base) si vous la connaissez." },
      { h2: "Passer dans LuxeFinder", body: "Uploadez la photo : l’app propose un cadrage modèle pour comparer des offres d’occasion / vendeurs — pas des catalogues de répliques." },
      { h2: "Ensuite", body: "Une fois le modèle nommé, croisez avec un guide « vrai ou faux » et exigez des photos récentes au vendeur." },
    ],
    related: ["reconnaitre-faux-keepall","vrai-ou-faux-keepall","identifier-modele-sac"],
  },
  {
    slug: "vrai-ou-faux-keepall",
    title: "Keepall Louis Vuitton : vrai ou faux ? Checklist",
    h1: "Keepall : vrai ou faux ?",
    description: "Checklist vrai/faux Keepall Louis Vuitton pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "« Keepall vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Keepall), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Louis Vuitton. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-keepall","identifier-keepall-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-birkin",
    title: "Comment reconnaître un faux Birkin Hermès (guide 2026)",
    h1: "Comment reconnaître un faux Birkin",
    description: "Signes d’un faux Birkin Hermès : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "Les contrefaçons de Birkin (Hermès) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Hermès. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Birkin se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Birkin", body: "Pour un Birkin Hermès : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Hermès. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-birkin-photo","vrai-ou-faux-birkin","identifier-modele-sac"],
  },

  {
    slug: "vrai-ou-faux-birkin",
    title: "Birkin Hermès : vrai ou faux ? Checklist",
    h1: "Birkin : vrai ou faux ?",
    description: "Checklist vrai/faux Birkin Hermès pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "« Birkin vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Birkin), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Hermès. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-birkin","identifier-birkin-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-kelly",
    title: "Comment reconnaître un faux Kelly Hermès (guide 2026)",
    h1: "Comment reconnaître un faux Kelly",
    description: "Signes d’un faux Kelly Hermès : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "Les contrefaçons de Kelly (Hermès) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Hermès. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Kelly se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Kelly", body: "Pour un Kelly Hermès : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Hermès. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-kelly-photo","vrai-ou-faux-kelly","identifier-modele-sac"],
  },
  {
    slug: "identifier-kelly-photo",
    title: "Identifier un Kelly Hermès sur photo",
    h1: "Identifier un Kelly à partir d’une photo",
    description: "Quel modèle est ce Kelly Hermès ? Angles utiles, détails à viser, puis analyse photo LuxeFinder.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "Mal nommer un Kelly fausse toute recherche d’occasion. Voici comment préparer une photo exploitable, puis laisser LuxeFinder proposer une identification.",
    sections: [
      { h2: "Angles qui comptent", body: "Face, profil, ouvert (intérieur), hardware, et une vue nette de la matière. Lumière naturelle, sans filtre agressif." },
      { h2: "Signaux Kelly", body: "Silhouette, anses, fermoir, proportions, toile ou cuir typiques du Kelly. Notez la taille approximative (ex. cm de base) si vous la connaissez." },
      { h2: "Passer dans LuxeFinder", body: "Uploadez la photo : l’app propose un cadrage modèle pour comparer des offres d’occasion / vendeurs — pas des catalogues de répliques." },
      { h2: "Ensuite", body: "Une fois le modèle nommé, croisez avec un guide « vrai ou faux » et exigez des photos récentes au vendeur." },
    ],
    related: ["reconnaitre-faux-kelly","vrai-ou-faux-kelly","identifier-modele-sac"],
  },
  {
    slug: "vrai-ou-faux-kelly",
    title: "Kelly Hermès : vrai ou faux ? Checklist",
    h1: "Kelly : vrai ou faux ?",
    description: "Checklist vrai/faux Kelly Hermès pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "« Kelly vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Kelly), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Hermès. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-kelly","identifier-kelly-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-picotin",
    title: "Comment reconnaître un faux Picotin Hermès (guide 2026)",
    h1: "Comment reconnaître un faux Picotin",
    description: "Signes d’un faux Picotin Hermès : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "Les contrefaçons de Picotin (Hermès) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Hermès. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Picotin se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Picotin", body: "Pour un Picotin Hermès : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Hermès. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-picotin-photo","vrai-ou-faux-picotin","identifier-modele-sac"],
  },
  {
    slug: "identifier-picotin-photo",
    title: "Identifier un Picotin Hermès sur photo",
    h1: "Identifier un Picotin à partir d’une photo",
    description: "Quel modèle est ce Picotin Hermès ? Angles utiles, détails à viser, puis analyse photo LuxeFinder.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "Mal nommer un Picotin fausse toute recherche d’occasion. Voici comment préparer une photo exploitable, puis laisser LuxeFinder proposer une identification.",
    sections: [
      { h2: "Angles qui comptent", body: "Face, profil, ouvert (intérieur), hardware, et une vue nette de la matière. Lumière naturelle, sans filtre agressif." },
      { h2: "Signaux Picotin", body: "Silhouette, anses, fermoir, proportions, toile ou cuir typiques du Picotin. Notez la taille approximative (ex. cm de base) si vous la connaissez." },
      { h2: "Passer dans LuxeFinder", body: "Uploadez la photo : l’app propose un cadrage modèle pour comparer des offres d’occasion / vendeurs — pas des catalogues de répliques." },
      { h2: "Ensuite", body: "Une fois le modèle nommé, croisez avec un guide « vrai ou faux » et exigez des photos récentes au vendeur." },
    ],
    related: ["reconnaitre-faux-picotin","vrai-ou-faux-picotin","identifier-modele-sac"],
  },
  {
    slug: "vrai-ou-faux-picotin",
    title: "Picotin Hermès : vrai ou faux ? Checklist",
    h1: "Picotin : vrai ou faux ?",
    description: "Checklist vrai/faux Picotin Hermès pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "« Picotin vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Picotin), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Hermès. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-picotin","identifier-picotin-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-classic-flap",
    title: "Comment reconnaître un faux Classic Flap Chanel (guide 2026)",
    h1: "Comment reconnaître un faux Classic Flap",
    description: "Signes d’un faux Classic Flap Chanel : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["chanel"],
    intro: "Les contrefaçons de Classic Flap (Chanel) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Chanel. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Classic Flap se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Classic Flap", body: "Pour un Classic Flap Chanel : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Chanel. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-classic-flap-photo","vrai-ou-faux-classic-flap","identifier-modele-sac"],
  },

  {
    slug: "vrai-ou-faux-classic-flap",
    title: "Classic Flap Chanel : vrai ou faux ? Checklist",
    h1: "Classic Flap : vrai ou faux ?",
    description: "Checklist vrai/faux Classic Flap Chanel pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["chanel"],
    intro: "« Classic Flap vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Classic Flap), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Chanel. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-classic-flap","identifier-classic-flap-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-woc",
    title: "Comment reconnaître un faux Wallet on Chain Chanel (guide 2026)",
    h1: "Comment reconnaître un faux Wallet on Chain",
    description: "Signes d’un faux Wallet on Chain Chanel : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["chanel"],
    intro: "Les contrefaçons de Wallet on Chain (Chanel) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Chanel. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Wallet on Chain se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Wallet on Chain", body: "Pour un Wallet on Chain Chanel : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Chanel. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-woc-photo","vrai-ou-faux-woc","identifier-modele-sac"],
  },
  {
    slug: "identifier-woc-photo",
    title: "Identifier un Wallet on Chain Chanel sur photo",
    h1: "Identifier un Wallet on Chain à partir d’une photo",
    description: "Quel modèle est ce Wallet on Chain Chanel ? Angles utiles, détails à viser, puis analyse photo LuxeFinder.",
    intent: "howto" as const,
    brands: ["chanel"],
    intro: "Mal nommer un Wallet on Chain fausse toute recherche d’occasion. Voici comment préparer une photo exploitable, puis laisser LuxeFinder proposer une identification.",
    sections: [
      { h2: "Angles qui comptent", body: "Face, profil, ouvert (intérieur), hardware, et une vue nette de la matière. Lumière naturelle, sans filtre agressif." },
      { h2: "Signaux Wallet on Chain", body: "Silhouette, anses, fermoir, proportions, toile ou cuir typiques du Wallet on Chain. Notez la taille approximative (ex. cm de base) si vous la connaissez." },
      { h2: "Passer dans LuxeFinder", body: "Uploadez la photo : l’app propose un cadrage modèle pour comparer des offres d’occasion / vendeurs — pas des catalogues de répliques." },
      { h2: "Ensuite", body: "Une fois le modèle nommé, croisez avec un guide « vrai ou faux » et exigez des photos récentes au vendeur." },
    ],
    related: ["reconnaitre-faux-woc","vrai-ou-faux-woc","identifier-modele-sac"],
  },
  {
    slug: "vrai-ou-faux-woc",
    title: "Wallet on Chain Chanel : vrai ou faux ? Checklist",
    h1: "Wallet on Chain : vrai ou faux ?",
    description: "Checklist vrai/faux Wallet on Chain Chanel pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["chanel"],
    intro: "« Wallet on Chain vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Wallet on Chain), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Chanel. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-woc","identifier-woc-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-re-edition-2005",
    title: "Comment reconnaître un faux Re-Edition 2005 Prada (guide 2026)",
    h1: "Comment reconnaître un faux Re-Edition 2005",
    description: "Signes d’un faux Re-Edition 2005 Prada : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["prada"],
    intro: "Les contrefaçons de Re-Edition 2005 (Prada) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Prada. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Re-Edition 2005 se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Re-Edition 2005", body: "Pour un Re-Edition 2005 Prada : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Prada. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-re-edition-2005-photo","vrai-ou-faux-re-edition-2005","identifier-modele-sac"],
  },
  {
    slug: "identifier-re-edition-2005-photo",
    title: "Identifier un Re-Edition 2005 Prada sur photo",
    h1: "Identifier un Re-Edition 2005 à partir d’une photo",
    description: "Quel modèle est ce Re-Edition 2005 Prada ? Angles utiles, détails à viser, puis analyse photo LuxeFinder.",
    intent: "howto" as const,
    brands: ["prada"],
    intro: "Mal nommer un Re-Edition 2005 fausse toute recherche d’occasion. Voici comment préparer une photo exploitable, puis laisser LuxeFinder proposer une identification.",
    sections: [
      { h2: "Angles qui comptent", body: "Face, profil, ouvert (intérieur), hardware, et une vue nette de la matière. Lumière naturelle, sans filtre agressif." },
      { h2: "Signaux Re-Edition 2005", body: "Silhouette, anses, fermoir, proportions, toile ou cuir typiques du Re-Edition 2005. Notez la taille approximative (ex. cm de base) si vous la connaissez." },
      { h2: "Passer dans LuxeFinder", body: "Uploadez la photo : l’app propose un cadrage modèle pour comparer des offres d’occasion / vendeurs — pas des catalogues de répliques." },
      { h2: "Ensuite", body: "Une fois le modèle nommé, croisez avec un guide « vrai ou faux » et exigez des photos récentes au vendeur." },
    ],
    related: ["reconnaitre-faux-re-edition-2005","vrai-ou-faux-re-edition-2005","identifier-modele-sac"],
  },
  {
    slug: "vrai-ou-faux-re-edition-2005",
    title: "Re-Edition 2005 Prada : vrai ou faux ? Checklist",
    h1: "Re-Edition 2005 : vrai ou faux ?",
    description: "Checklist vrai/faux Re-Edition 2005 Prada pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["prada"],
    intro: "« Re-Edition 2005 vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Re-Edition 2005), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Prada. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-re-edition-2005","identifier-re-edition-2005-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-loulou",
    title: "Comment reconnaître un faux Loulou Saint Laurent (guide 2026)",
    h1: "Comment reconnaître un faux Loulou",
    description: "Signes d’un faux Loulou Saint Laurent : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["ysl"],
    intro: "Les contrefaçons de Loulou (Saint Laurent) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Saint Laurent. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai Loulou se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle Loulou", body: "Pour un Loulou Saint Laurent : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Saint Laurent. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-loulou-photo","vrai-ou-faux-loulou","identifier-modele-sac"],
  },
  {
    slug: "identifier-loulou-photo",
    title: "Identifier un Loulou Saint Laurent sur photo",
    h1: "Identifier un Loulou à partir d’une photo",
    description: "Quel modèle est ce Loulou Saint Laurent ? Angles utiles, détails à viser, puis analyse photo LuxeFinder.",
    intent: "howto" as const,
    brands: ["ysl"],
    intro: "Mal nommer un Loulou fausse toute recherche d’occasion. Voici comment préparer une photo exploitable, puis laisser LuxeFinder proposer une identification.",
    sections: [
      { h2: "Angles qui comptent", body: "Face, profil, ouvert (intérieur), hardware, et une vue nette de la matière. Lumière naturelle, sans filtre agressif." },
      { h2: "Signaux Loulou", body: "Silhouette, anses, fermoir, proportions, toile ou cuir typiques du Loulou. Notez la taille approximative (ex. cm de base) si vous la connaissez." },
      { h2: "Passer dans LuxeFinder", body: "Uploadez la photo : l’app propose un cadrage modèle pour comparer des offres d’occasion / vendeurs — pas des catalogues de répliques." },
      { h2: "Ensuite", body: "Une fois le modèle nommé, croisez avec un guide « vrai ou faux » et exigez des photos récentes au vendeur." },
    ],
    related: ["reconnaitre-faux-loulou","vrai-ou-faux-loulou","identifier-modele-sac"],
  },
  {
    slug: "vrai-ou-faux-loulou",
    title: "Loulou Saint Laurent : vrai ou faux ? Checklist",
    h1: "Loulou : vrai ou faux ?",
    description: "Checklist vrai/faux Loulou Saint Laurent pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["ysl"],
    intro: "« Loulou vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (Loulou), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Saint Laurent. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-loulou","identifier-loulou-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "reconnaitre-faux-marmont",
    title: "Comment reconnaître un faux GG Marmont Gucci (guide 2026)",
    h1: "Comment reconnaître un faux GG Marmont",
    description: "Signes d’un faux GG Marmont Gucci : coutures, hardware, matière, cohérence. Méthode LuxeFinder + photo.",
    intent: "howto" as const,
    brands: ["gucci"],
    intro: "Les contrefaçons de GG Marmont (Gucci) circulent beaucoup en seconde main. Ce guide donne une méthode d’observation — sans affiliation à Gucci. L’objectif : éviter une mauvaise affaire, pas trouver où acheter une imitation.",
    sections: [
      { h2: "Observer la cohérence d’ensemble", body: "Un vrai GG Marmont se juge sur plusieurs points à la fois (silhouette, matière, coutures, ferrures). Un seul détail « OK » ne prouve rien. Méfiez-vous d’un prix anormalement bas sur un modèle iconique." },
      { h2: "Points de contrôle GG Marmont", body: "Pour un GG Marmont Gucci : alignez matelassage ou toile, netteté des marquages, poids et gravure du hardware, régularité des coutures, odeur et grain du cuir. Photographiez face, profil, intérieur et gros plans." },
      { h2: "Ce que LuxeFinder change", body: "Déposez une photo dans LuxeFinder pour cadrer le modèle avant d’acheter en occasion. L’outil aide à nommer la pièce ; il ne remplace pas une expertise physique pour les pièces à fort enjeu." },
      { h2: "Avertissement", body: "LuxeFinder n’est pas affilié à Gucci. Nous ne vendons pas de contrefaçons et ne recommandons aucun site d’imitations. En cas de doute, passez par une plateforme d’occasion authentifiant ou un expert." },
    ],
    related: ["identifier-marmont-photo","vrai-ou-faux-marmont","identifier-modele-sac"],
  },
  {
    slug: "identifier-marmont-photo",
    title: "Identifier un GG Marmont Gucci sur photo",
    h1: "Identifier un GG Marmont à partir d’une photo",
    description: "Quel modèle est ce GG Marmont Gucci ? Angles utiles, détails à viser, puis analyse photo LuxeFinder.",
    intent: "howto" as const,
    brands: ["gucci"],
    intro: "Mal nommer un GG Marmont fausse toute recherche d’occasion. Voici comment préparer une photo exploitable, puis laisser LuxeFinder proposer une identification.",
    sections: [
      { h2: "Angles qui comptent", body: "Face, profil, ouvert (intérieur), hardware, et une vue nette de la matière. Lumière naturelle, sans filtre agressif." },
      { h2: "Signaux GG Marmont", body: "Silhouette, anses, fermoir, proportions, toile ou cuir typiques du GG Marmont. Notez la taille approximative (ex. cm de base) si vous la connaissez." },
      { h2: "Passer dans LuxeFinder", body: "Uploadez la photo : l’app propose un cadrage modèle pour comparer des offres d’occasion / vendeurs — pas des catalogues de répliques." },
      { h2: "Ensuite", body: "Une fois le modèle nommé, croisez avec un guide « vrai ou faux » et exigez des photos récentes au vendeur." },
    ],
    related: ["reconnaitre-faux-marmont","vrai-ou-faux-marmont","identifier-modele-sac"],
  },
  {
    slug: "vrai-ou-faux-marmont",
    title: "GG Marmont Gucci : vrai ou faux ? Checklist",
    h1: "GG Marmont : vrai ou faux ?",
    description: "Checklist vrai/faux GG Marmont Gucci pour l’occasion. Puis vérifiez le modèle en photo avec LuxeFinder.",
    intent: "howto" as const,
    brands: ["gucci"],
    intro: "« GG Marmont vrai ou faux » revient sans cesse avant un achat seconde main. Utilisez cette checklist, puis une photo pour confirmer le modèle.",
    sections: [
      { h2: "Checklist rapide", body: "Marquages nets, coutures régulières, hardware cohérent, matière crédible, provenance documentée. Un doute sur deux points = pause." },
      { h2: "Pièges fréquents", body: "Cartes d’authenticité trop belles, stickers refaits, photos catalogue uniquement, prix « trop beaux ». Demandez des clichés datés avec un objet de référence." },
      { h2: "LuxeFinder", body: "Identifiez d’abord le bon modèle (GG Marmont), puis comparez des pistes d’achat légitimes (occasion / vendeurs)." },
      { h2: "Disclaimer", body: "Contenu informatif, sans affiliation Gucci. Pas de facilitation d’achat de contrefaçon." },
    ],
    related: ["reconnaitre-faux-marmont","identifier-marmont-photo","eviter-arnaques-vendeurs"],
  },
  {
    slug: "authentifier-louis-vuitton",
    title: "Authentifier Louis Vuitton : méthode pratique (occasion)",
    h1: "Authentifier un article Louis Vuitton",
    description: "Méthode pour authentifier Louis Vuitton en seconde main : photos, cohérence, limites. LuxeFinder pour l’ID modèle.",
    intent: "howto" as const,
    brands: ["louis-vuitton"],
    intro: "Authentifier Louis Vuitton demande méthode et prudence. Voici un cadre utile avant expertise — LuxeFinder aide surtout à identifier le modèle sur photo.",
    sections: [
      { h2: "Preuves à collecter", body: "Photos haute résolution, numéro/série si pertinent, facture si dispo, historique vendeur. Ne publiez jamais un numéro complet en clair." },
      { h2: "Limites du DIY", body: "Les superfakes trompent même des acheteurs expérimentés. Au-delà d’un certain budget, passez par une plateforme qui authentifie ou un expert." },
      { h2: "Rôle de LuxeFinder", body: "Cadrer le modèle (Birkin vs Kelly, Speedy vs Keepall, etc.) avant de négocier. Ce n’est pas un certificat d’authenticité officiel." },
      { h2: "Disclaimer", body: "Pas d’affiliation à Louis Vuitton. Objectif : réduire les erreurs d’achat en occasion." },
    ],
    related: ["identifier-modele-sac","eviter-arnaques-vendeurs","budget-sac-luxe"],
  },
  {
    slug: "authentifier-hermes",
    title: "Authentifier Hermès : méthode pratique (occasion)",
    h1: "Authentifier un article Hermès",
    description: "Méthode pour authentifier Hermès en seconde main : photos, cohérence, limites. LuxeFinder pour l’ID modèle.",
    intent: "howto" as const,
    brands: ["hermes"],
    intro: "Authentifier Hermès demande méthode et prudence. Voici un cadre utile avant expertise — LuxeFinder aide surtout à identifier le modèle sur photo.",
    sections: [
      { h2: "Preuves à collecter", body: "Photos haute résolution, numéro/série si pertinent, facture si dispo, historique vendeur. Ne publiez jamais un numéro complet en clair." },
      { h2: "Limites du DIY", body: "Les superfakes trompent même des acheteurs expérimentés. Au-delà d’un certain budget, passez par une plateforme qui authentifie ou un expert." },
      { h2: "Rôle de LuxeFinder", body: "Cadrer le modèle (Birkin vs Kelly, Speedy vs Keepall, etc.) avant de négocier. Ce n’est pas un certificat d’authenticité officiel." },
      { h2: "Disclaimer", body: "Pas d’affiliation à Hermès. Objectif : réduire les erreurs d’achat en occasion." },
    ],
    related: ["identifier-modele-sac","eviter-arnaques-vendeurs","budget-sac-luxe"],
  },
  {
    slug: "authentifier-chanel",
    title: "Authentifier Chanel : méthode pratique (occasion)",
    h1: "Authentifier un article Chanel",
    description: "Méthode pour authentifier Chanel en seconde main : photos, cohérence, limites. LuxeFinder pour l’ID modèle.",
    intent: "howto" as const,
    brands: ["chanel"],
    intro: "Authentifier Chanel demande méthode et prudence. Voici un cadre utile avant expertise — LuxeFinder aide surtout à identifier le modèle sur photo.",
    sections: [
      { h2: "Preuves à collecter", body: "Photos haute résolution, numéro/série si pertinent, facture si dispo, historique vendeur. Ne publiez jamais un numéro complet en clair." },
      { h2: "Limites du DIY", body: "Les superfakes trompent même des acheteurs expérimentés. Au-delà d’un certain budget, passez par une plateforme qui authentifie ou un expert." },
      { h2: "Rôle de LuxeFinder", body: "Cadrer le modèle (Birkin vs Kelly, Speedy vs Keepall, etc.) avant de négocier. Ce n’est pas un certificat d’authenticité officiel." },
      { h2: "Disclaimer", body: "Pas d’affiliation à Chanel. Objectif : réduire les erreurs d’achat en occasion." },
    ],
    related: ["identifier-modele-sac","eviter-arnaques-vendeurs","budget-sac-luxe"],
  },
  {
    slug: "vestiaire-collective-vs-vinted",
    title: "Vestiaire Collective vs Vinted : lequel pour le luxe occasion ?",
    h1: "Vestiaire Collective vs Vinted",
    description: "Frais, authenticité, vitesse de vente : comparer Vestiaire et Vinted pour sacs de luxe d’occasion. Angle neutre LuxeFinder.",
    intent: "howto" as const,
    brands: [],
    intro: "Vinted et Vestiaire Collective ne jouent pas dans la même cour. Voici une comparaison factuelle pour décider où acheter ou revendre un sac de luxe.",
    sections: [
      { h2: "Positionnement", body: "Vinted : volume, mode du quotidien, frais vendeur nuls. Vestiaire : luxe curator, authentification plus structurée, commissions vendeur." },
      { h2: "Quand choisir quoi", body: "Pièce iconique à fort prix : Vestiaire (ou équivalent authentifiant). Article mid / vitesse : Vinted, avec photos et vigilance accrues." },
      { h2: "LuxeFinder dans le parcours", body: "Identifiez d’abord le modèle sur photo, puis choisissez la place de marché. LuxeFinder ne remplace pas l’auth plateforme." },
      { h2: "Neutralité", body: "Aucune affiliation. Les frais évoluent : vérifiez toujours les grilles officielles avant de vendre." },
    ],
    related: ["budget-sac-luxe","trouver-vendeur-sac-luxe","eviter-arnaques-vendeurs"],
  }
];
