/** Mid-tail batch — plan 50 pages (guides). See docs/seo/plan-seo-50-pages-luxefinder.md */

type PageSection = { h2: string; body: string };
type SeoPage = {
  slug: string;
  title: string;
  h1: string;
  description: string;
  intent: "howto" | "brand" | "model" | "buy";
  intro: string;
  sections: PageSection[];
  brands?: string[];
  related: string[];
};

export const SEO_MIDTAIL_BATCH: SeoPage[] = [
  {
    slug: "code-date-louis-vuitton",
    title: "Code date Louis Vuitton : le lire et le vérifier",
    h1: "Code date Louis Vuitton : le lire, le vérifier (et après 2021)",
    description: "Où trouver le code date LV, comment le décoder par époque, et ce qui change avec la puce RFID depuis 2021. Guide FR.",
    intent: "howto",
    brands: ["louis_vuitton"],
    intro: "Le code date Louis Vuitton aide à dater un sac et à situer l’usine — ce n’est pas un numéro de série unique. Depuis 2021, beaucoup de pièces n’ont plus de code visible : la puce RFID prend le relais. Voici comment lire, vérifier, et ce que ça prouve vraiment.",
    sections: [
      { h2: "À quoi sert le code date (≠ numéro de série)", body: "Le code date indique une période de fabrication et un site de production. Il ne rend pas le sac « unique » comme un numéro de châssis. Un code plausible n’authentifie pas à lui seul : les contrefaçons le reproduisent. Utilisez-le comme un indice dans un faisceau (coutures, toile, hardware, vachetta)." },
      { h2: "Où le trouver selon le modèle", body: "Selon Speedy, Neverfull, Alma ou Pochette Métis, le marquage est souvent sur une étiquette intérieure cousue, parfois près d’une poche. Demandez toujours une macro nette du marquage + une photo de l’emplacement dans le sac. Si le vendeur refuse, c’est un signal d’alerte." },
      { h2: "Décoder lettres et chiffres par période", body: "Avant 1990, les formats sont plus variables. De 1990 à 2006, on croise souvent lettres d’usine + chiffres de mois/année selon des schémas connus des collectionneurs. De 2007 à début 2021, le format évolue encore (ordre mois/année). Notez la période estimée et croisez-la avec le style du modèle (hardware, doublure)." },
      { h2: "Depuis 2021 : plus de code, place à la puce", body: "Pour beaucoup de pièces post-mars 2021, l’absence de code date visible n’est pas un « faux automatique » : LV a basculé vers d’autres marquages / puce. Inversement, un « code date » trop parfait sur un modèle clairement récent peut être incohérent. Datation + style + provenance > un seul marquage." },
      { h2: "Code date valide ≠ sac authentique : les pièges", body: "Les faux copient les codes. Un code d’usine improbable pour le modèle, une étiquette mal cousue, une typographie irrégulière, ou un code qui ne correspond pas à l’époque du hardware sont des red flags. Le code est un filtre, pas un certificat." },
      { h2: "Tableau mental des contrôles usine", body: "Notez : (1) présence/absence cohérente avec l’année, (2) couture de l’étiquette, (3) lisibilité sans « trop neuf » suspect sur un sac usé, (4) cohérence avec toile et vachetta. Documentez ces points avant de payer." },
      { h2: "Vérifier en 2 minutes avec une photo", body: "Prenez ou exigez une photo nette du marquage + face du sac. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["reconnaitre-vrai-louis-vuitton","faire-authentifier-un-sac","louis-vuitton-occasion","prix-neverfull-occasion"],
  },
  {
    slug: "speedy-25-30-35-quelle-taille",
    title: "Speedy 25, 30 ou 35 : quelle taille choisir",
    h1: "Speedy 25, 30 ou 35 : quelle taille choisir (+ prix occasion)",
    description: "Comparatif Speedy 25 vs 30 vs 35 : dimensions, contenance, bandoulière, et écarts de prix en occasion.",
    intent: "howto",
    brands: ["louis_vuitton"],
    intro: "La Speedy change radicalement selon la taille. Le SERP regorge de fiches produit : ici, on compare usage réel, contenance et ce que ça change sur le prix d’occasion — avant de lancer une recherche.",
    sections: [
      { h2: "Dimensions exactes et poids", body: "La 25 est un format quotidien compact ; la 30 reste le classic « tout-terrain » ; la 35 devient un vrai cabas de week-end. Demandez la longueur de base en cm si le vendeur dit seulement « Speedy ». Le poids à vide monte avec la taille et la toile." },
      { h2: "Ce qui rentre vraiment dedans", body: "Test mental : téléphone, portefeuille, petit flacon, éventuellement une petite trousse. La 25 sature vite. La 30 accepte un format A5 / petite bouteille. La 35 vise journée complète. Si vous avez besoin d’un A4 plat, vérifiez plutôt Neverfull ou OnTheGo." },
      { h2: "Speedy vs Speedy Bandoulière", body: "Le « Speedy B » ajoute une bandoulière : plus polyvalent, souvent plus cher en occasion. Confirmez la présence de la bandoulière et de ses points d’attache sur photos récentes du lot — pas sur un catalogue générique." },
      { h2: "Quelle taille selon morphologie et usage", body: "Petit gabarit / ville : 25. Quotidien mixte : 30. Voyage court / plus de volume : 35. Portez en main vs épaule change le confort : la bandoulière compte autant que les cm." },
      { h2: "Prix occasion par taille et par toile", body: "En général : plus grande ≠ toujours plus chère si l’état est moyen. Mono, Damier et Épi n’ont pas la même liquidité. Les prix « trop beaux » sur une 30 mono impeccable méritent une vérification renforcée. Relevez 5 annonces comparables (taille + toile + état) avant d’offrir." },
      { h2: "Laquelle se revend le mieux", body: "La 30 reste très liquide. La 25 attire un usage mode. La 35 se revend bien si l’état des coins et des anses est propre. Gardez facture/boîte si vous les avez : ça aide à la revente, sans garantir l’authenticité." },
      { h2: "Trouver la vôtre au bon prix", body: "Cadrez taille + toile + budget, puis comparez plusieurs offres. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["speedy-taille-offres","code-date-louis-vuitton","louis-vuitton-vintage","prix-neverfull-occasion"],
  },
  {
    slug: "taille-neverfull-pm-mm-gm",
    title: "Neverfull PM, MM ou GM : comparatif des tailles",
    h1: "Neverfull PM, MM ou GM : les tailles comparées",
    description: "Différences Neverfull PM / MM / GM : dimensions, usage quotidien, pochette, et impact sur le prix d’occasion.",
    intent: "howto",
    brands: ["louis_vuitton"],
    intro: "Neverfull MM ou GM est l’une des questions les plus posées avant un achat d’occasion. Voici un comparatif orienté usage et prix — pas une fiche produit.",
    sections: [
      { h2: "Les 3 tailles en chiffres", body: "PM = compact, MM = standard quotidien, GM = grand volume. Demandez toujours les dimensions intérieures utiles (pas seulement le marketing). Une photo avec un objet de référence (bouteille, livre) aide plus qu’un adjectif « grand »." },
      { h2: "Porté et gabarits", body: "Au porté, la GM peut paraître très large sur petite morphologie. La MM reste le compromis travail/week-end. La PM convient mieux en city bag léger. L’ouverture haute et les côtés souples changent la tenue une fois remplie." },
      { h2: "La pochette : ce qui change selon les années", body: "Certaines générations incluent une pochette intérieure amovible / convertible. Vérifiez sa présence et son état : une pochette manquante peut justifier une négociation, sans être un « faux »." },
      { h2: "MM ou GM pour le quotidien / le travail", body: "Ordinateur 13\" : testez ou demandez un avis honnête — beaucoup de GM le permettent, MM selon housse. Pour un usage léger, MM évite le « trop de sac ». Pour voyage / enfants / sport, GM gagne." },
      { h2: "Prix occasion par taille", body: "La MM est souvent la plus liquide. La GM peut coûter plus cher en excellent état, mais une GM abîmée aux coins se négocie. Comparez taille + toile + état intérieur, pas le titre d’annonce seul." },
      { h2: "Disponibilité boutique et effet sur l’occasion", body: "Quand un modèle est moins facile à trouver en boutique, l’occasion peut tendre. Inverse aussi : surplus d’annonces → prix plus souples. Suivez le marché sur 2–3 plateformes avant d’acheter dans l’urgence." },
      { h2: "Comparer les offres", body: "Fixez PM/MM/GM + toile + budget max. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["prix-neverfull-occasion","code-date-louis-vuitton","identifier-neverfull-photo","louis-vuitton-occasion"],
  },
  {
    slug: "augmentation-prix-chanel",
    title: "Augmentation des prix Chanel : historique et effet occasion",
    h1: "Prix Chanel : l’historique des augmentations (et l’effet sur l’occasion)",
    description: "Hausses de prix Chanel, impact neuf vs occasion, Timeless/Boy/WOC : comprendre l’écart avant d’acheter d’occasion.",
    intent: "buy",
    brands: ["chanel"],
    intro: "Chanel augmente régulièrement ses prix neufs. Comprendre l’historique aide à juger si une occasion est « bien placée » — sans croire au mythe que tout Chanel monte toujours.",
    sections: [
      { h2: "Historique des hausses par modèle", body: "Timeless / Classic Flap, Boy, 19 et WOC n’ont pas la même trajectoire. Notez l’année de référence du prix neuf annoncé par le vendeur : un « prix boutique » obsolète fausse la comparaison. Preférez des relevés récents et datés." },
      { h2: "Pourquoi Chanel augmente", body: "Positionnement, demande, coûts, stratégie de rareté perçue. Pour l’acheteur occasion, l’important est l’écart neuf/occasion actuel, pas le storytelling de marque." },
      { h2: "Neuf vs occasion : l’écart réel aujourd’hui", body: "L’occasion peut sembler « une affaire » après une hausse — ou rester chère si la demande est forte. Caviar vs agneau, taille, complétude (carte, boîte) changent l’écart. Construisez une fourchette sur 8–10 annonces comparables." },
      { h2: "Acheter d’occasion avant ou après une hausse ?", body: "Après une hausse, certains vendeurs réévaluent immédiatement ; d’autres pas. Négociez sur l’état et la rareté réelle, pas sur la dernière une presse." },
      { h2: "Ce que ça change pour la revente", body: "Tous les Chanel ne sont pas des « investissements ». Le Timeless tient souvent mieux que des lignes plus mode. L’état et les accessoires pèsent plus qu’un titre d’annonce." },
      { h2: "Payer le juste prix en occasion", body: "Cadrez modèle + taille + cuir + budget. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["prix-chanel-timeless-occasion","numero-serie-chanel","chanel-occasion","sac-de-luxe-investissement"],
  },
  {
    slug: "numero-serie-chanel",
    title: "Numéro de série Chanel : hologramme, carte et puce",
    h1: "Numéro de série, hologramme et puce Chanel : vérifier son sac",
    description: "Où trouver le numéro Chanel, correspondance années, carte d’authenticité, puce métallique depuis 2021, limites des faux.",
    intent: "howto",
    brands: ["chanel"],
    intro: "Le numéro de série Chanel (autocollant / hologramme, puis évolutions vers puce) est un outil de datation — pas une preuve absolue. Voici comment le lire et pourquoi il ne suffit jamais seul.",
    sections: [
      { h2: "Où trouver le numéro (hologramme)", body: "Souvent à l’intérieur, sur un sticker. Demandez une macro nette + photo de l’emplacement. Un numéro flou, recollé, ou incohérent avec l’usure du sac est un red flag." },
      { h2: "Correspondance numéro ↔ année", body: "Des tableaux de correspondance existent chez les spécialistes (préfixe / époque). Utilisez-les pour estimer une période, puis croisez avec le style (quincaillerie, doublure, logo). Un tableau seul ne remplace pas l’œil sur coutures et cuir." },
      { h2: "La carte d’authenticité : ce qu’elle prouve (et ne prouve pas)", body: "La carte peut accompagner le sac ; elle se perd, se copie, et ne « valide » pas un faux. L’absence de carte sur un vintage n’est pas rédhibitoire. L’incohérence carte ↔ numéro ↔ sac l’est." },
      { h2: "Depuis 2021 : la puce métallique", body: "Chanel a évolué vers des dispositifs anti-contrefaçon plus modernes. Un sac récent sans les marquages attendus pour son époque mérite prudence. Inversement, n’exigez pas un hologramme « années 90 » sur une pièce clairement 2020s." },
      { h2: "Numéro valide ≠ sac vrai : les arnaques courantes", body: "Numéros clonés, stickers re-collés, photos de catalogue. Exigez des photos du lot réel sous plusieurs angles, y compris coins et chaîne." },
      { h2: "Vérifier par photo", body: "Regroupez face, intérieur, numéro, hardware. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["prix-chanel-timeless-occasion","sac-chanel-vintage","faire-authentifier-un-sac","chanel-occasion"],
  },
  {
    slug: "prix-chanel-timeless-occasion",
    title: "Prix Chanel Timeless / Classic Flap d’occasion",
    h1: "Prix d’un Chanel Timeless / Classic Flap d’occasion",
    description: "Argus Timeless occasion : small/medium/jumbo, caviar vs agneau, vintage vs récent, état et complétude.",
    intent: "buy",
    brands: ["chanel"],
    intro: "Le Timeless (Classic Flap) domine les recherches de prix Chanel occasion. Voici comment construire une fourchette réaliste — taille, cuir, époque, état — plutôt que de croire un seul listing.",
    sections: [
      { h2: "Fourchettes par taille", body: "Small, medium et jumbo n’ont pas le même marché. Comparez strictement la même taille. Un medium « bon marché » face à des small n’est pas une affaire." },
      { h2: "Caviar vs agneau : impact prix", body: "Le caviar résiste mieux au quotidien ; l’agneau marque plus vite. En occasion, un agneau très marqué doit décoter. Le choix influe aussi sur la revente." },
      { h2: "Vintage vs récent", body: "Le vintage peut coter selon quincaillerie et rareté, mais l’état du cuir et les restaurations comptent. Un « vintage parfait » à prix cassé mérite double vérification." },
      { h2: "État et complétude", body: "Carte, boîte, dustbag, facture : utiles, jamais suffisants. Priorisez l’état réel du matelassé, de la chaîne et des coins." },
      { h2: "Où se joue l’écart neuf/occasion", body: "Après les hausses boutique, l’écart peut sembler large — jusqu’à ce que la demande occasion suive. Datez vos relevés (mois/année) quand vous notez des prix." },
      { h2: "Exemples de méthode de relevé", body: "Prenez 8 annonces filtrées (taille+cuir+état), écartez extrêmes (suspect bas / vendeur pro hors marché), calculez une médiane. C’est plus honnête qu’un « prix moyen » inventé." },
      { h2: "Payer le juste prix", body: "Fixez taille + cuir + budget. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["augmentation-prix-chanel","numero-serie-chanel","chanel-caviar-ou-agneau","classic-flap-trouver-vendeur"],
  },
  {
    slug: "prix-neverfull-occasion",
    title: "Prix Neverfull occasion : tailles, toiles, années",
    h1: "Prix d’une Neverfull d’occasion (par taille, toile et année)",
    description: "Cote Neverfull occasion PM/MM/GM, monogram/damier, signaux prix trop bas, méthode de comparaison.",
    intent: "buy",
    brands: ["louis_vuitton"],
    intro: "Les listings Neverfull ne donnent pas de repère. Construisez un argus simple : taille × toile × état — et méfiez-vous des prix irréalistes.",
    sections: [
      { h2: "Fourchettes par taille (PM/MM/GM)", body: "Comparez toujours la même taille. La MM est la plus liquide ; la GM dépend fortement de l’état des coins et de l’intérieur." },
      { h2: "Par toile (monogram, damier, azur, épi)", body: "Certaines toiles circulent plus. Une toile rare abîmée peut valoir moins qu’une mono propre. Filtrez les annonces par toile avant de juger le prix." },
      { h2: "L’effet rareté / disponibilité", body: "Quand le neuf est moins accessible, l’occasion peut tendre. Vérifiez sur plusieurs plateformes le même week-end pour éviter un biais d’une seule annonce." },
      { h2: "Ce qui fait baisser le prix", body: "Coins écrasés, anses détendues, intérieur sale, odeur, pochette manquante, réparation visible. Ces défauts sont normaux en occasion — ils doivent se voir dans le prix." },
      { h2: "Prix trop bas = signal d’alerte", body: "Un écart violent vs la médiane du marché, photos de catalogue, vendeur pressé : ralentissez. Demandez macros code date / marquages et photos du lot." },
      { h2: "Trouver au juste prix", body: "Taille + toile + budget max. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["taille-neverfull-pm-mm-gm","code-date-louis-vuitton","sac-de-luxe-vinted","identifier-neverfull-photo"],
  },
  {
    slug: "reconnaitre-vrai-louis-vuitton",
    title: "Reconnaître un vrai Louis Vuitton : points de contrôle",
    h1: "Reconnaître un vrai sac Louis Vuitton : les points de contrôle",
    description: "Checklist authenticité LV : monogram, coutures, vachetta, marquages, hardware. Limites des superfakes et vérification photo.",
    intent: "howto",
    brands: ["louis_vuitton"],
    intro: "Reconnaître un vrai Louis Vuitton demande un faisceau d’indices. L’œil nu a des limites face aux meilleurs faux : voici une méthode honnête, orientée acheteur d’occasion.",
    sections: [
      { h2: "La méthode du faisceau d’indices", body: "Aucun point isolé ne suffit. Toile + alignement + coutures + vachetta + marquages + hardware + provenance. Plus les signaux divergent, plus le risque monte." },
      { h2: "Toile et alignement du monogram", body: "Sur monogram, regardez symétrie et continuité des motifs aux coutures. Des décalages grossiers sont suspects ; des « presque parfaits » existent aussi sur les bons faux — d’où le faisceau." },
      { h2: "Coutures et finitions", body: "Points réguliers, tension, finitions des bords. Comparez avec des références de la même époque. Une couture « trop belle » sur un sac très usé peut être incohérente." },
      { h2: "Vachetta, patine et tranches", body: "La vachetta vieillit. Une patine artificielle uniforme ou une vachetta « neuve » sur un sac soi-disant ancien méritent questions. Voir aussi le guide vachetta." },
      { h2: "Marquages, code date et puce", body: "Cohérence époque ↔ marquages. Un code date « parfait » ne sauve pas un hardware faux." },
      { h2: "Quincaillerie et fermetures", body: "Gravures, couleur, symétrie des zips, qualité des anneaux. Macros indispensables." },
      { h2: "Les superfakes : limites de l’œil nu", body: "Certains faux passent un scroll rapide. En cas de doute sur un montant élevé : authentification pro ou passez. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["code-date-louis-vuitton","faire-authentifier-un-sac","sac-de-luxe-vinted","cuir-vachetta-louis-vuitton"],
  },
  {
    slug: "premier-sac-de-luxe",
    title: "Premier sac de luxe : lequel choisir (occasion)",
    h1: "Premier sac de luxe : lequel choisir (et pourquoi l’occasion)",
    description: "Choisir un premier sac de luxe par budget (500 / 1000 / 2000 €), tenue de cote, pièges, occasion vs neuf.",
    intent: "buy",
    intro: "Le premier sac de luxe n’a pas besoin d’être une icône inaccessible. Voici une grille par budget, orientée occasion et revente — pas un moodboard magazine.",
    sections: [
      { h2: "Les critères qui comptent vraiment", body: "Usage, taille, entretien, liquidité à la revente, et authenticité. Le logo « Instagram » seul est un mauvais critère d’achat." },
      { h2: "Moins de 500 €", body: "Pistes : petites pièces / vintage / lignes plus accessibles en bon état. Soyez ultra-strict sur l’auth : c’est la zone des faux « prix d’appel »." },
      { h2: "500 à 1 000 €", body: "Speedy, Alma, certaines lignes Gucci/YSL/Prada en occasion propre. Comparez toujours l’état des coins et le total rendu." },
      { h2: "1 000 à 2 000 €", body: "Meilleure profondeur de marché (Neverfull, Métis, certaines Chanel entrée selon état). Gardez une marge pour authentification si le montant est élevé." },
      { h2: "Neuf vs occasion : le calcul", body: "Occasion = décote possible + risque auth. Neuf = prix plein + garantie boutique. Pour un premier achat, l’occasion bien vérifiée est souvent le meilleur apprentissage." },
      { h2: "Les valeurs sûres qui se revendent", body: "Modèles iconiques liquides (Speedy 30, certaines Classic Flap, etc.) se revendent plus facilement que les pièces très mode." },
      { h2: "Les pièges du premier achat", body: "Pression vendeur, photos catalogue, prix trop bas, absence de macros. Ralentissez." },
      { h2: "Trouver le vôtre par budget", body: "Indiquez une fourchette claire. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["sac-de-luxe-moins-1000-euros","meilleurs-sites-sac-luxe-occasion","sac-de-luxe-investissement","etat-sac-occasion"],
  },
  {
    slug: "sac-de-luxe-moins-1000-euros",
    title: "Sac de luxe à moins de 1 000 € en occasion",
    h1: "Quel sac de luxe pour moins de 1 000 € (en occasion)",
    description: "Sélection occasion sous 1000 € : LV, Gucci, YSL, Prada, vintage. Ce qu’on ne trouve pas (Chanel/Hermès) et comment éviter les faux.",
    intent: "buy",
    intro: "Sous 1 000 € en occasion, on trouve de vraies pièces — et beaucoup de pièges. Voici une sélection réaliste et ce qu’il ne faut pas espérer à ce budget.",
    sections: [
      { h2: "Méthodo et prix relevés", body: "Filtrez par état « bon / très bon », ignorez les titres « neuf » suspects. Comparez 5 annonces par modèle avant de conclure." },
      { h2: "Louis Vuitton sous 1 000 €", body: "Selon marché : petites pièces, certains Alma/Speedy selon état et toile, accessoires. Les iconiques « parfaits » sous le marché = prudence extrême." },
      { h2: "Gucci et Saint Laurent sous 1 000 €", body: "Marmont, Jackie vintage, Loulou selon taille/état : souvent plus accessibles. Vérifiez série et usure du matelassé." },
      { h2: "Prada, Fendi et le vintage malin", body: "Re-Edition, Galleria d’occasion, Baguette vintage : bons terrains si vous acceptez l’usure et vérifiez l’auth." },
      { h2: "Ce qu’on ne trouve pas à ce budget", body: "Chanel Timeless récent impeccable et Hermès iconiques « bons marchés » sont en général hors zone — méfiez-vous des exceptions trop belles." },
      { h2: "Éviter les faux à petit prix", body: "Budget bas + marque ultra-copiée = checklist photo stricte. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["premier-sac-de-luxe","sac-de-luxe-vinted","numero-serie-gucci","faire-authentifier-un-sac"],
  },
  {
    slug: "meilleurs-sites-sac-luxe-occasion",
    title: "Meilleurs sites pour acheter un sac de luxe d’occasion",
    h1: "Meilleurs sites pour acheter un sac de luxe d’occasion (comparatif)",
    description: "Comparatif plateformes occasion luxe : frais, authentification, retours, pour quel sac choisir quel site.",
    intent: "howto",
    intro: "Vinted, Vestiaire, dépôts-vente, spécialistes : chaque canal a des frais et un niveau de contrôle différent. Voici un comparatif honnête pour choisir selon votre sac et votre budget.",
    sections: [
      { h2: "Tableau comparatif (commissions, authentification, retours)", body: "Notez pour chaque site : frais acheteur/vendeur, promesse d’auth, délai, politique de retour. Un « contrôle qualité » marketing n’est pas une garantie absolue." },
      { h2: "Marketplaces généralistes vs spécialistes", body: "Généralistes = volume + risque variable. Spécialistes = plus de process, parfois plus cher. Votre urgence et votre appétit au risque décident." },
      { h2: "Dépôts-vente et revendeurs pro", body: "Utile pour voir/toucher. Demandez la politique d’authentification écrite et les recours." },
      { h2: "Acheter à l’étranger (Japon, UE)", body: "Économie possible, mais douane/TVA/livraison. Voir le guide Japon pour le calcul complet." },
      { h2: "Quel site selon votre sac et votre budget", body: "Petit budget / apprentissage : canaux avec bons recours. Gros ticket Hermès/Chanel : process auth renforcé + patience." },
      { h2: "Les signaux d’un vendeur fiable", body: "Photos du lot, réponses précises, historique, pas de pression. Croisez le prix à la cote." },
      { h2: "Chercher partout en une fois", body: "Plutôt que de multiplier les onglets sans méthode. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["sac-de-luxe-vinted","vestiaire-collective-fiable","acheter-sac-luxe-japon","faire-authentifier-un-sac"],
  },
  {
    slug: "sac-de-luxe-vinted",
    title: "Sac de luxe sur Vinted : risques et vérifications",
    h1: "Acheter un sac de luxe sur Vinted : bonne idée ? (risques et vérifications)",
    description: "Vinted et sacs de luxe : ce que couvre la vérification, red flags, photos à exiger, litiges, méthode avant paiement.",
    intent: "howto",
    intro: "On trouve de bonnes affaires sur Vinted — et des faux. Voici un mode d’emploi concret, sans clickbait peur, pour réduire le risque.",
    sections: [
      { h2: "Ce que Vinted vérifie (et ne vérifie pas)", body: "Le service de vérification a un périmètre : lisez-le pour la catégorie luxe au moment de votre achat. Ce n’est pas une authentification maison de marque. Gardez des preuves écrites." },
      { h2: "Les red flags d’une annonce", body: "Prix hors sol, photos catalogue, refus de macros, pression, compte récent multi-marques iconiques." },
      { h2: "Les photos à demander avant d’acheter", body: "Face, profil, coins, anses, intérieur, marquages/série, hardware. Sans ça, ne payez pas un ticket élevé." },
      { h2: "Prix cohérent : comparer à la cote", body: "Alignez 5 annonces comparables hors Vinted aussi. Un « deal » isolé est souvent un piège." },
      { h2: "Litiges et remboursements : la vraie procédure", body: "Agissez dans les délais de la plateforme, documentez avec photos à réception, ne laissez pas expirer la protection." },
      { h2: "Vérifier par photo avant de payer", body: "Même sur Vinted, commencez par identifier le modèle et juger le risque. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["meilleurs-sites-sac-luxe-occasion","reconnaitre-vrai-louis-vuitton","numero-serie-chanel","prix-neverfull-occasion"],
  },
  {
    slug: "kelly-vs-birkin",
    title: "Kelly ou Birkin : les vraies différences",
    h1: "Kelly ou Birkin : les vraies différences (guide éducatif)",
    description: "Différence Kelly vs Birkin : porté, tailles, prix occasion, accès boutique. Guide éducatif sans promesse d’investissement.",
    intent: "howto",
    brands: ["hermes"],
    intro: "Kelly et Birkin sont souvent confondus. Voici les différences d’usage et de marché occasion — ton éducatif, sans « Birkin pas chère » ni promesse financière.",
    sections: [
      { h2: "Histoire express des deux icônes", body: "Deux silhouettes Hermès iconiques, deux histoires, un marché occasion très surveillé. L’essentiel pour l’acheteur : forme, porté, taille, cuir, complétude." },
      { h2: "Forme et porté : ce qui change au quotidien", body: "Le Birkin s’ouvre plus « cabas » ; le Kelly est plus structuré avec son rabat et son cadenas caractéristique. Le confort dépend de la taille et de la bandoulière." },
      { h2: "Tailles et cuirs courants", body: "25/30/35… et cuirs changent le prix plus que le storytelling. Exigez taille et type de cuir par écrit." },
      { h2: "Prix : boutique vs occasion, la réalité", body: "L’accès boutique est contraint ; l’occasion peut être au-dessus du prix boutique selon rareté. Méfiez-vous des prix « trop accessibles »." },
      { h2: "Lequel pour quel usage", body: "Besoin d’ouverture rapide et volume : plutôt Birkin. Look plus formel / rabat : plutôt Kelly. Essayez les tailles en photos portées." },
      { h2: "Se procurer l’un ou l’autre : les voies possibles", body: "Boutique (selon disponibilité), occasion spécialisée, vigilance maximale sur les canaux non pro." },
      { h2: "Vigilance contrefaçon", body: "Ticket élevé = authentification renforcée. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["prix-birkin-occasion","prix-kelly-occasion","faire-authentifier-un-sac","hermes-occasion"],
  },
  {
    slug: "faire-authentifier-un-sac",
    title: "Faire authentifier un sac de luxe : services, prix, délais",
    h1: "Faire authentifier un sac de luxe : services, prix et délais",
    description: "Qui authentifie un sac (et qui ne le fait pas), photo vs physique, prix/délais, valeur d’un certificat, quand ça vaut le coup.",
    intent: "howto",
    intro: "Les maisons n’authentifient en général pas les pièces d’occasion pour le public. Voici les options réelles (expert, service photo, plateforme) et quand payer pour une auth.",
    sections: [
      { h2: "Qui peut authentifier (et qui ne peut pas)", body: "Experts indépendants, services en ligne sur photos, contrôles de certaines plateformes. Louis Vuitton / Chanel ne « valident » pas votre occasion comme un certificat public systématique." },
      { h2: "Authentification par photos vs physique", body: "La photo est rapide et utile en pré-achat. Le physique reste plus fort sur cas limites. Pour un gros ticket, combinez." },
      { h2: "Prix et délais constatés", body: "Varient selon service et marque. Demandez le délai écrit et ce qui est livré (avis, rapport). Méfiez-vous des « authentifications » gratuites floues sur réseaux." },
      { h2: "Que vaut un certificat juridiquement", body: "Un avis d’expert aide à la décision et parfois à la revente ; ce n’est pas une magie juridique universelle. Gardez factures et échanges." },
      { h2: "Avant achat vs après achat", body: "Avant : conditionnez l’achat. Après : utile si doute, mais le recours dépend du canal d’achat." },
      { h2: "Vérification instantanée par photo", body: "Pour cadrer le modèle et démarrer une short-list. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["reconnaitre-vrai-louis-vuitton","numero-serie-chanel","numero-serie-gucci","sac-de-luxe-vinted"],
  },
  {
    slug: "identifier-sac-photo",
    title: "Identifier et estimer un sac à partir d’une photo",
    h1: "Identifier et estimer un sac à partir d’une photo",
    description: "Photo → modèle → cote → offres : méthode pour identifier un sac de luxe avant d’acheter.",
    intent: "howto",
    intro: "La page produit de LuxeFinder en version guide : passer d’une photo à un modèle nommé, puis à une fourchette et des offres comparables.",
    sections: [
      { h2: "Pourquoi identifier avant d’acheter ou de vendre", body: "Sans le bon nom de modèle, vous comparez des prix incomparables et vous exposez aux listings trompeurs." },
      { h2: "Les indices lisibles sur une photo", body: "Silhouette, quincaillerie, toile/cuir, logo, coutures, proportions. Exigez plusieurs angles, pas une seule face marketing." },
      { h2: "Démo : de la photo au modèle exact", body: "Isolez 2–3 candidats, éliminez par détails (fermoir, matelassé, marquages). Documentez votre conclusion." },
      { h2: "De l’identification à la cote", body: "Relevez des annonces du même modèle/état. Écartez les extrêmes suspects." },
      { h2: "Les cas difficiles", body: "Vintage, collabs, éditions limitées : plus d’expertise, plus de prudence sur le prix « trop beau »." },
      { h2: "Essayer avec votre photo", body: "Uploadez une photo et un budget. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["faire-authentifier-un-sac","identifier-neverfull-photo","deposer-photo-sac-trouver-offre","meilleurs-sites-sac-luxe-occasion"],
  },
  {
    slug: "prix-birkin-occasion",
    title: "Prix Birkin d’occasion : réalité du marché",
    h1: "Prix d’un sac Birkin d’occasion : la réalité du marché",
    description: "Fourchettes Birkin occasion par taille et cuir, écart boutique, vigilance. Guide éducatif.",
    intent: "buy",
    brands: ["hermes"],
    intro: "Marché opaque et risqué. Lecture éducative des prix — sans promesse d’investissement ni « Birkin pas chère ».",
    sections: [
      { h2: "Pourquoi l’occasion coûte parfois plus cher que la boutique", body: "Accès contraint + demande : l’occasion reflète la rareté perçue, pas un discount automatique." },
      { h2: "Fourchettes par taille (25/30/35)", body: "Comparez la même taille et un cuir comparable. Les écarts sont énormes d’une annonce à l’autre." },
      { h2: "Impact du cuir et de la couleur", body: "Certains cuirs/couleurs sont plus liquides. Exigez le détail par écrit avant de comparer." },
      { h2: "État, année, boîte et facture", body: "La complétude aide ; l’état réel prime. Un kit complet sur un faux reste un faux." },
      { h2: "Le mythe de l’investissement garanti", body: "Beaucoup de pièces ne montent pas comme on le raconte. Budget que vous acceptez de immobiliser." },
      { h2: "Acheter sans se faire avoir", body: "Ticket très élevé = authentification renforcée. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["kelly-vs-birkin","prix-kelly-occasion","faire-authentifier-un-sac","hermes-occasion"],
  },
  {
    slug: "prix-kelly-occasion",
    title: "Prix Kelly Hermès d’occasion",
    h1: "Prix d’un Kelly d’occasion",
    description: "Argus Kelly occasion : tailles, sellier vs retourné, vintage, documents vendeur.",
    intent: "buy",
    brands: ["hermes"],
    intro: "Du vintage plus accessible (selon état) aux pièces récentes très chères : méthode de fourchette et vigilance.",
    sections: [
      { h2: "Fourchettes par taille (20/25/28/32)", body: "Ne mélangez pas les tailles dans votre relevé de prix." },
      { h2: "Sellier vs retourné : impact prix", body: "La construction change look et souvent prix. Demandez le type explicitement." },
      { h2: "Le cas des Kelly vintage", body: "Parfois plus accessibles ; usure et restaurations à inspecter." },
      { h2: "Cuirs et décote", body: "Cuir marqué = prix marqué. Macros coins et rabat." },
      { h2: "Complétude (bandoulière, cadenas, clochette)", body: "Listez ce qui est inclus. Une bandoulière manquante se négocie." },
      { h2: "Vérifier avant d’acheter", body: "Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["kelly-vs-birkin","prix-birkin-occasion","faire-authentifier-un-sac","hermes-occasion"],
  },
  {
    slug: "sac-chanel-vintage",
    title: "Sac Chanel vintage : guide d’achat",
    h1: "Sac Chanel vintage : le guide d’achat",
    description: "Acheter Chanel vintage : dater via numéro, prix par époque, état, pièges des sacs restaurés.",
    intent: "buy",
    brands: ["chanel"],
    intro: "Le vintage Chanel cote selon époque et état — et attire restaurations / repeints vendus comme « excellent ». Repères concrets.",
    sections: [
      { h2: "Pourquoi le Chanel vintage cote", body: "Quincaillerie, cuirs, rareté de certaines années. Ce n’est pas vrai pour toutes les pièces abîmées." },
      { h2: "Dater un Chanel : numéro ↔ année", body: "Utilisez le guide numéro de série, puis croisez le style." },
      { h2: "Spécificités 80s/90s", body: "Quincaillerie et cuirs diffèrent des pièces récentes. Apprenez les signaux de l’époque visée." },
      { h2: "Prix par époque et modèle", body: "Relevez des annonces de la même décennie + taille. Écartez les extrêmes." },
      { h2: "Quel état tolérer", body: "Usure honnête OK ; déformations graves et odeurs = négociation ou passage." },
      { h2: "Le piège des sacs restaurés/repeints", body: "Demandez l’historique. Un cuir « trop parfait » sur un vintage mérite questions." },
      { h2: "Chercher un vintage fiable", body: "Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["numero-serie-chanel","prix-chanel-timeless-occasion","augmentation-prix-chanel","chanel-occasion"],
  },
  {
    slug: "louis-vuitton-vintage",
    title: "Louis Vuitton vintage : le guide",
    h1: "Louis Vuitton vintage : le guide",
    description: "LV vintage : modèles recherchés, datation, patine vachetta, prix, éviter les faux vintage.",
    intent: "buy",
    brands: ["louis_vuitton"],
    intro: "Speedy, Noé, Papillon, Sac Plat… le vintage LV a ses pépites et ses pièges (doublure, restauration, faux « old look »).",
    sections: [
      { h2: "Les modèles vintage recherchés", body: "Priorisez les silhouettes liquides et l’état structurel (anses, coins, toile)." },
      { h2: "Prix constatés par modèle", body: "Comparez modèle + taille + état. Un Speedy vintage « cadeau » est souvent un signal d’alerte." },
      { h2: "Dater un LV vintage", body: "Codes anciens, marquages Made in France, style hardware. Voir code date." },
      { h2: "Patine et vachetta : que tolérer", body: "Patine miel OK ; taches irrégulières et cuir craquelé se négocient. Guide vachetta." },
      { h2: "Jus d’origine vs restauré", body: "Restauration possible, mais doit être déclarée et reflétée dans le prix." },
      { h2: "Éviter les faux vintage", body: "Faisceau d’indices + auth si ticket élevé. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["code-date-louis-vuitton","speedy-25-30-35-quelle-taille","cuir-vachetta-louis-vuitton","reparation-sac-louis-vuitton"],
  },
  {
    slug: "chanel-caviar-ou-agneau",
    title: "Cuir caviar ou agneau Chanel : lequel choisir",
    h1: "Cuir caviar ou agneau (Chanel) : lequel choisir en occasion",
    description: "Caviar vs agneau Chanel : vieillissement, entretien, impact prix occasion, juger l’état sur photos.",
    intent: "howto",
    brands: ["chanel"],
    intro: "En occasion, le cuir décide du prix autant que la taille. Caviar vs agneau : usage, marques, décote.",
    sections: [
      { h2: "Différences visuelles et au toucher", body: "Caviar = grainé résistant ; agneau = plus souple, marque plus vite." },
      { h2: "Vieillissement comparé", body: "Sur 5–10 ans, l’agneau montre rides et shiny spots ; le caviar garde mieux une allure « propre » au quotidien." },
      { h2: "Impact sur le prix occasion", body: "Un agneau très marqué doit coûter moins. Un caviar impeccable se revend souvent plus facilement." },
      { h2: "Quel cuir pour un usage quotidien", body: "Quotidien rude → caviar. Occasion / look dressy → agneau possible si vous acceptez les marques." },
      { h2: "Entretien de chaque cuir", body: "Évitez les recettes agressives. Stockage à l’abri, dustbag, pas d’humidité." },
      { h2: "Juger l’état sur les photos d’une annonce", body: "Exigez macros coins, rabat, zones de contact chaîne. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["prix-chanel-timeless-occasion","sac-chanel-vintage","numero-serie-chanel","augmentation-prix-chanel"],
  },
  {
    slug: "numero-serie-gucci",
    title: "Numéro de série Gucci : vérifier un sac",
    h1: "Numéro de série Gucci : vérifier un sac",
    description: "Lire l’étiquette série Gucci, formats par époque, QR code, limites : numéro valide ≠ authenticité.",
    intent: "howto",
    brands: ["gucci"],
    intro: "L’étiquette à deux lignes Gucci aide à cadrer modèle/fournisseur — les faux la recopient. Méthode de lecture et limites.",
    sections: [
      { h2: "Où trouver l’étiquette de série", body: "Intérieur, couture intérieure. Macro nette + contexte dans le sac." },
      { h2: "Lire les deux lignes", body: "Une ligne référence modèle/matériaux, l’autre info production selon époque. Notez-les pour croiser avec le modèle annoncé." },
      { h2: "Typographies et formats par époque", body: "Les polices et espacements évoluent. Une étiquette « générique » mal imprimée est un red flag." },
      { h2: "Le QR code des modèles récents", body: "Présent sur certaines pièces récentes ; absence sur un vintage n’est pas un faux automatique." },
      { h2: "Numéro valide ≠ sac authentique", body: "Les numéros se clonent. Ajoutez hardware, toile, coutures, provenance." },
      { h2: "Vérifier par photo", body: "Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["gucci-occasion","faire-authentifier-un-sac","sac-de-luxe-moins-1000-euros","arnaques-sacs-luxe-occasion"],
  },
  {
    slug: "sac-de-luxe-investissement",
    title: "Sacs de luxe qui prennent (vraiment) de la valeur",
    h1: "Les sacs de luxe qui prennent (vraiment) de la valeur",
    description: "Investissement sac de luxe : lesquels tiennent leur cote, lesquels décotent, neuf vs occasion, facteurs état.",
    intent: "buy",
    intro: "La majorité des sacs décotent. Voici une lecture honnête : ce qui tient, ce qui monte parfois, et pourquoi « tout Chanel monte » est un mythe.",
    sections: [
      { h2: "La vérité : la majorité des sacs décotent", body: "Mode, usure, volume d’annonces : beaucoup de pièces perdent de la valeur dès la sortie boutique." },
      { h2: "Ceux qui tiennent leur valeur (et pourquoi)", body: "Icônes liquides, demande stable, taille/cuir recherchés. Même là, l’état décide." },
      { h2: "Les rares qui montent", body: "Certains Hermès / pièces très contraintes — marché spéculatif et risqué. Pas un conseil financier." },
      { h2: "Neuf ou occasion pour « investir »", body: "Occasion peut éviter la première décote — ou intégrer une prime de rareté. Calculez frais + auth." },
      { h2: "État et complétude : les vrais facteurs", body: "Coins, hardware, odeur, kit : plus décisifs qu’un titre « investissement »." },
      { h2: "Suivre la cote d’un modèle", body: "Identifiez le modèle exact puis comparez des offres datées. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["augmentation-prix-chanel","prix-birkin-occasion","premier-sac-de-luxe","etat-sac-occasion"],
  },
  {
    slug: "authentifier-sac-dior",
    title: "Authentifier un sac Dior : codes et gravures",
    h1: "Authentifier un sac Dior : codes et gravures",
    description: "Code date Dior, gravures, charms, vintage vs récent : guide FR pour vérifier un sac Dior d’occasion.",
    intent: "howto",
    brands: ["dior"],
    intro: "Marquages Dior par époque : où les trouver, comment les lire, et pourquoi un code seul ne prouve pas l’authenticité.",
    sections: [
      { h2: "Où trouver le code date Dior", body: "Souvent intérieur / sur un marquage dédié selon modèle. Macro + emplacement." },
      { h2: "Lire le code (usine + période)", body: "Les formats varient selon les années. Servez-vous-en pour dater, puis croisez le style (cannage, charms, quincaillerie)." },
      { h2: "Gravures et typographies par époque", body: "« Christian Dior Paris » et variantes : cohérence typographique attendue pour l’époque." },
      { h2: "Charms et quincaillerie", body: "Sur Lady Dior notamment, l’usure des charms est courante ; des charms « trop neufs » sur un sac usé interrogent." },
      { h2: "Vintage vs récent : ce qui change", body: "N’exigez pas les mêmes signaux. La datation évite les faux raisonnements." },
      { h2: "Vérifier par photo", body: "Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["book-tote-budget","faire-authentifier-un-sac","dior","sac-luxe-occasion-france"],
  },
  {
    slug: "acheter-sac-luxe-japon",
    title: "Acheter un sac Louis Vuitton au Japon : bonne affaire ?",
    h1: "Acheter un sac Louis Vuitton au Japon : vraie bonne affaire ?",
    description: "Prix Japon + livraison + douane/TVA : calcul complet, grades japonais, risques vs offres locales.",
    intent: "howto",
    intro: "Le Japon fascine pour l’état et le grading. Voici le calcul complet FR : économie réelle après frais, ou mirage.",
    sections: [
      { h2: "Pourquoi le Japon fascine", body: "Culture du grading, pièces souvent très propres, taux de change parfois favorable." },
      { h2: "Le vrai calcul : prix + livraison + douane + TVA", body: "Additionnez tout avant de crier à l’affaire. Un « -30 % » peut disparaître après import." },
      { h2: "Acheter sur place vs à distance", body: "Sur place : inspection. À distance : photos, vendeur, recours plus complexes." },
      { h2: "Les grades japonais expliqués", body: "N/S/A/AB… varient selon boutiques. Demandez la légende du vendeur + photos des défauts." },
      { h2: "Risques et recours", body: "Litige international = plus dur. Préférez canaux avec protection claire." },
      { h2: "Comparer avec les offres locales", body: "Parfois le local gagne après frais. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["meilleurs-sites-sac-luxe-occasion","etat-sac-occasion","reconnaitre-vrai-louis-vuitton","louis-vuitton-occasion"],
  },
  {
    slug: "vestiaire-collective-fiable",
    title: "Vestiaire Collective : fiable pour un sac de luxe ?",
    h1: "Vestiaire Collective : fiable pour un sac de luxe ?",
    description: "Fonctionnement du contrôle qualité Vestiaire, frais, litiges, quand acheter ou non. Ton factuel.",
    intent: "howto",
    intro: "Avis polarisés en ligne. Voici un angle factuel : process, frais, limites — pour décider si Vestiaire convient à votre achat.",
    sections: [
      { h2: "Comment fonctionne le contrôle qualité", body: "Lisez le process actuel (auth / QC) pour la catégorie. Ce n’est pas une garantie absolue universelle." },
      { h2: "Frais et commissions réels", body: "Intégrez frais acheteur éventuels et comparaison au prix « ailleurs »." },
      { h2: "Ce que disent les litiges documentés", body: "Des litiges existent sur toute grande plateforme. Documentez, respectez les délais, gardez les preuves." },
      { h2: "Vendre vs acheter : deux expériences", body: "Les délais et frictions diffèrent. Lisez les conditions du moment." },
      { h2: "Quand Vestiaire est le bon choix (et quand non)", body: "Bon pour certains tickets avec process ; parfois un spécialiste ou une inspection locale est plus sage." },
      { h2: "Vérifier une annonce avant d’enchérir", body: "Photos + cote + modèle exact. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["meilleurs-sites-sac-luxe-occasion","sac-de-luxe-vinted","faire-authentifier-un-sac","etat-sac-occasion"],
  },
  {
    slug: "reparation-sac-louis-vuitton",
    title: "Réparer un sac Louis Vuitton : prix, délais, options",
    h1: "Réparer un sac Louis Vuitton : prix, délais, options",
    description: "Réparation LV maison vs artisans : prix, délais, réparable ou non, impact cote, angle acheteur occasion.",
    intent: "howto",
    brands: ["louis_vuitton"],
    intro: "Une occasion « à défauts » peut être rentable… ou un gouffre. Maison LV vs artisans : cadre pour décider.",
    sections: [
      { h2: "Ce que répare Louis Vuitton (et à quel prix)", body: "Devis selon pièce et politique du moment. Sans facture, certains services sont limités — demandez en amont." },
      { h2: "Artisans indépendants : quand et pour quoi", body: "Utile pour certains travaux ; impact possible sur la perception à la revente. Transparence obligatoire." },
      { h2: "Réparable vs irrécupérable", body: "Toile déchirée structurelle, moisissure avancée, déformation grave : parfois mieux de passer." },
      { h2: "Le calcul : occasion abîmée + réparation", body: "Prix achat + devis + délai vs une pièce déjà propre. Souvent le propre gagne." },
      { h2: "Impact d’une réparation sur la cote", body: "Réparation visible / non maison peut décoter. Déclarez-la à la revente." },
      { h2: "Estimer un sac à défauts", body: "Identifiez le modèle puis jugez le coût des défauts. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["louis-vuitton-vintage","cuir-vachetta-louis-vuitton","etat-sac-occasion","prix-neverfull-occasion"],
  },
  {
    slug: "cuir-vachetta-louis-vuitton",
    title: "Vachetta et patine Louis Vuitton : entretenir et évaluer",
    h1: "Vachetta et patine Louis Vuitton : entretenir et évaluer",
    description: "Cuir vachetta LV : échelle de patine, taches, entretien, impact prix occasion, juger sur photos.",
    intent: "howto",
    brands: ["louis_vuitton"],
    intro: "La vachetta raconte la vie du sac. Voici une échelle pour juger une annonce et ce qui se nettoie vraiment.",
    sections: [
      { h2: "C’est quoi la vachetta", body: "Cuir naturel des anses/accents qui fonce avec lumière, peaux et temps." },
      { h2: "L’échelle de patine", body: "Neuve → miel → foncée → tachée/irrégulière. Chaque cran a un impact prix différent selon les acheteurs." },
      { h2: "Ce qui se nettoie (et ce qui ne part pas)", body: "Certaines taches d’eau/transfert sont tenaces. Méfiez-vous des « avant/après » miracles sur réseaux." },
      { h2: "Entretenir sans abîmer", body: "Évitez produits agressifs. Stockage propre, éviter pluie répétée." },
      { h2: "Patine et prix : l’impact réel", body: "Une patine homogène plait ; des auréoles se négocient." },
      { h2: "Évaluer la vachetta d’une annonce", body: "Demandez macros anses et coins. Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["reconnaitre-vrai-louis-vuitton","louis-vuitton-vintage","reparation-sac-louis-vuitton","code-date-louis-vuitton"],
  },
  {
    slug: "etat-sac-occasion",
    title: "États d’un sac d’occasion : grille de lecture",
    h1: "États d’un sac d’occasion : la grille de lecture",
    description: "Comme neuf, très bon, bon, correct + grades japonais : décote et défauts cachés. Grille LuxeFinder.",
    intent: "howto",
    intro: "« Très bon état » ne veut pas dire la même chose partout. Traduction concrète des grades et impact prix.",
    sections: [
      { h2: "Pourquoi les grades varient d’un site à l’autre", body: "Marketing vendeur ≠ standard unique. Demandez des photos des défauts, pas seulement le label." },
      { h2: "La grille LuxeFinder", body: "Comme neuf : usure quasi invisible. Très bon : micro-marques. Bon : usure claire mais structure OK. Correct : défauts visibles à négocier." },
      { h2: "Correspondance avec les grades japonais", body: "N/S/A/AB… : demandez la légende du vendeur + photos." },
      { h2: "Décote moyenne par niveau d’état", body: "Plus le modèle est iconique, plus un état moyen se vend — mais moins cher. Inversement, un état « correct » sur pièce rare reste risqué." },
      { h2: "Les défauts cachés que les photos ne montrent pas", body: "Odeur, glue intérieure, déformation : posez la question et exigez une vidéo si ticket élevé." },
      { h2: "Juger l’état depuis une annonce", body: "Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["acheter-sac-luxe-japon","reparation-sac-louis-vuitton","prix-neverfull-occasion","meilleurs-sites-sac-luxe-occasion"],
  },
  {
    slug: "sac-luxe-homme",
    title: "Sac de luxe homme : guide occasion",
    h1: "Sac de luxe homme : le guide occasion",
    description: "Sacs luxe homme en occasion : Keepall, sacoches, budgets 300/700/1500 €, modèles contrefaits, où chercher.",
    intent: "buy",
    intro: "Le SERP parle surtout neuf. Voici un guide occasion homme : modèles liquides, budgets, contrôles.",
    sections: [
      { h2: "Les modèles homme qui se trouvent en occasion", body: "Keepall, sacoches LV, certaines lignes Gucci/BV, messengers. Clarifiez dimensions cabine si voyage." },
      { h2: "Par budget (300 / 700 / 1 500 €)", body: "Plus le budget est bas, plus l’auth doit être stricte. À 1 500 €, exigez macros et éventuellement auth." },
      { h2: "Toiles et cuirs qui vieillissent bien", body: "Certaines toiles encaissent mieux le quotidien. Inspectez poignées et coins." },
      { h2: "Authentifier les modèles homme les plus copiés", body: "Keepall et sacoches iconiques sont très copiés. Faisceau d’indices." },
      { h2: "Où chercher", body: "Plateformes + pro + grading Japon selon le calcul de frais." },
      { h2: "Lancer une recherche", body: "Sur LuxeFinder, déposez une photo et votre budget pour comparer des offres de vendeurs — sans acheter à l’aveugle." },
    ],
    related: ["meilleurs-sites-sac-luxe-occasion","sac-de-luxe-moins-1000-euros","louis-vuitton-occasion","etat-sac-occasion"],
  },
];
